### ISSUE TITLE
Avoid one more opcode-based switch

### ISSUE THREAD

**Issue by AlexeySotkin** [KhronosGroup/SPIRV-LLVM-Translator#1072]
I'd like to avoid one more opcode-based switch. But to make it work we should change `SPIRVSelect` to inherit it from `SPIRVInstTemplateBase`, which is probably out of scope for this PR. Other than that, LGTM.

_Originally posted by @AlexeySotkin in https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1070#discussion_r649882432_

**Comment by svenvh** [comment]
I'll have a look at this.

PR #1073 adds some more cases to the opcode switch, so we also need to change the inheritance for those classes.  I don't expect we need to modify any more classes, as it's the last PR in my series to improve `OpSpecConstantOp` handling with integer operators.
