### ISSUE TITLE
Incorrect signedness for read_image/write_image

### ISSUE THREAD

**Issue by Weiwei-2021** [KhronosGroup/SPIRV-LLVM-Translator#1198]
When converting the follwing spirv to llvm ir:

`%uint = OpTypeInt 32 0

%v2uint = OpTypeVector %uint 2

%vec = OpCompositeInsert %v2uint ...

OpImageWrite %dst  %vec  %11`

The resulting llvm ir create a write_imagei instead of write_imageui, but the texel should be unsigned. 

And then we find a lit test named "image_signedness.ll" which marks as XFAIL. The lit test comments that "translator doesn't handle signedness for read_image/write_image yet". Any reason the translator cannot handle it?

**Comment by StuartDBrady** [comment]
As stated in the [OpenCL SPIR-V Environment Specification § 2.5.1 Basic Scalar and Vector Types](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_Env.html#_basic_scalar_and_vector_types):

> The following scalar types are supported by OpenCL environments:
> * **OpTypeBool**
> * **OpTypeInt**, with _Width_ equal to 8, 16, 32, or 64, and with _Signedness_ equal to zero, indicating no signedness semantics.
> * **OpTypeFloat**, with _Width_ equal to 16, 32, or 64.

Therefore, the "_OpTypeInt_ 32 0" here  should not be interpreted as being unsigned, but rather, the signedness is not specified.  (See also: [unsigned verses signed integers](https://www.khronos.org/registry/SPIR-V/specs/unified1/SPIRV.html#_a_id_unsignedsigned_a_unsigned_versus_signed_integers).)

When translating _OpImageRead_, the correct signedness is not known, unless the _SignExtend_ or _ZeroExtend_ [image operand](https://www.khronos.org/registry/SPIR-V/specs/unified1/SPIRV.html#Image_Operands) is used.  These image operand bit values were missing before to SPIR-V 1.4.  Where the value would not need to be extended, it's not clear if use of _SignExtend_ nor _ZeroExtend_ is permitted to meet the requirements in the OpenCL C spec that:

> `read_imagei`/`read_imageui` can only be used with image objects created with `image_channel_data_type` set to one of the following values: [...]

It's also not clear (to me) that these image operands would help at all with _OpImageWrite_.

Note that this SPIR-V/LLVM Translator does not translate SPIR-V into OpenCL C.  Instead, it translates into LLVM IR making use of an OpenCL C built-in function library, but we are free to relax the specification of these functions: it is then the responsibility of implementations making use of the translator to ensure they are compatible with the translator's relaxed use of these functions.

There is the concern here that the correct translation of the use of images requires SPIR-V 1.4.  We should ensure that the translator provides the option to report and error (which should perhaps be enabled by default, with an option to disable the error reporting) when images are used in a way that does not allow an unambiguous translation, i.e. where important signedness information would be lost in the translation.

I would welcome views as to whether it would be good to encourage the adoption of SPIR-V 1.4 for OpenCL as to better support images.

**Comment by Weiwei-2021** [comment]
Thank you for the detailed explaination! Based on [OpenCL SPIR-V Environment Specification § 2.5.1 Basic Scalar and Vector Types](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_Env.html#_basic_scalar_and_vector_types). It seems that the translator chooses to default the OpImageWrite to llvm's write_imagei since it cannot decide the signdness. but this default choice happens to be signed integer from llvm's perspective.

> Where the value would not need to be extended, it's not clear if use of SignExtend nor ZeroExtend is permitted to meet the requirements in the OpenCL C spec that:
> >read_imagei/read_imageui can only be used with image objects created with image_channel_data_type set to one of the following values: [...]

In the above spirv case, the host side may have "image_channel_data_type = CL_UNSIGNED_INT32". Currently, because the OpImageWrite is treated as "no signedness semantices", and converted to llvm's write_imagei intrinsic (_Z12write_imagei...). The following llvm compilation flow treats this write_imagei intrinsic as signed, which will caused undefined behavior based OpenCL's spec. OpImageRead should have the same problem.

So it looks like that _SignExtend_ and _ZeroExtend_ are needed to provide the signdness imformation on the kernel side, similar to LLVM's parameter attribute _zeroext_ and _signext_. It the specified _SignExtend_/_ZeroExtend disagrees with host side's image_channel_data_type, that would be a case which is an mistake made by spirv/opencl's deverloper. 

A side question is that if the spirv thinks the _OpIntType_ is "no signedness senmatics", does it mean that it accepts any image_channel_data_type signdness? In another word, should we check whether the signdness on the kernel side matchs the data_type on the host side?

> Note that this SPIR-V/LLVM Translator does not translate SPIR-V into OpenCL C. Instead, it translates into LLVM IR making use of an OpenCL C built-in function library, but we are free to relax the specification of these functions: it is then the responsibility of implementations making use of the translator to ensure they are compatible with the translator's relaxed use of these functions.
>I would welcome views as to whether it would be good to encourage the adoption of SPIR-V 1.4 for OpenCL so as to better support images.

If the _OpIntType 32 0_ is defined as "no signdness sematic", it is really hard to pick "i" or "ui". Image operand can be the correct solution to problems like this.
