### ISSUE TITLE
NoSignedWrap decoration is emitted without declaring SPV_KHR_no_integer_wrap_decoration

### ISSUE THREAD

**Issue by bader** [KhronosGroup/SPIRV-LLVM-Translator#120]
(re-posting from [SYCL compiler issue #2](https://github.com/intel/llvm/issues/2))
In cases when the translator emits NoSignedWrap decoration the SPV_KHR_no_integer_wrap_decoration isn't declared with an OpExtension.

**Comment by airlied** [comment]
@Fznamznon looks like your commit needs some fixes.

**Comment by AlexeySotkin** [comment]
These decorations are part of the core spec now. Why do we need to declare the extension ? Maybe spirv-val needs another update.

**Comment by AlexeySotkin** [comment]
I think the translator doesn't emit OpExtension properly in general, for any extension, not just for this one.

**Comment by kpet** [comment]
Is anyone looking at this? This issue makes it impossible to get useful feedback from the validator on many modules.

**Comment by AlexeySotkin** [comment]
I have it in my backlog.

**Comment by kpet** [comment]
Happy to hear that :). Thanks!

**Comment by AlexeySachkov** [comment]
Hi, I'm working on extensions support in SPIRV-Translator right now, feel free to review and leave your feedback in #175
