### ISSUE TITLE
Invalid SPIR-V generated for OpenCL C blocks (starting from 1.4 version)

### ISSUE THREAD

**Issue by MrSidims** [KhronosGroup/SPIRV-LLVM-Translator#1205]
During testing of https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1177 I observed, that test/transcoding/global_block.cl starts to fail (spirv-val) with:
```
error: line 63: Interface variable id <13> is used by entry point 'block_kernel' id <24>, but is not listed as an interface
 %__block_literal_global = OpVariable %_ptr_CrossWorkgroup__struct_10 CrossWorkgroup %11
```
due a following change in the spec:
```
A.34 Changes from Version 1.3
• New Functionality:
– Public issue #35: OpEntryPoint must list all global variables in the interface. Additionally, duplication in the list is not
allowed.
```
I haven't dug much into it, but since SPIR-V doesn't have 'blocks' it means that something is missed in our workaround.

**Comment by StuartDBrady** [comment]
Closing as this is a specific instance of issue #1216, which is a more general problem than described here.

**Comment by StuartDBrady** [comment]
OpenCL C code blocks are compiled and translated in a way that requires _CrossWorkgroup_ block literals.  Once _CrossWorkgroup_ variables are correctly listed in the _Interface_ for _OpEntryPoint_ for SPIR-V 1.4 and later, code using OpenCL C should validate successfully with no further action needed.

**Comment by MrSidims** [comment]
Thanks Stuart!
