### ISSUE TITLE
SPIR-V 1.4: Interface variables not listed in Interface of OpEntryPoint

### ISSUE THREAD

**Issue by StuartDBrady** [KhronosGroup/SPIRV-LLVM-Translator#1216]
When run on SPIR-V 1.4 output produced by the translator, the SPIR-V Validator may report errors of the following form:

> error: line _n_: Interface variable id <_var_id_> is used by entry point '_name_' id <_kernel_id_>, but it is not listed as an interface
>   `%out = OpVariable %_ptr_UniformConstant_type UniformConstant %type`

This can be reproduced with a trivial program using a `__constant` variable (i.e. using the _UniformConstant_ storage class), such as:
```
__constant int var = 0;
__kernel void test()
{
    (void)(var * 2);
}
```

resulting in the LLVM IR:
```
  %1 = load i32, i32 addrspace(2)* @var.const, align 4
  %2 = mul nsw i32 %1, 2
```
It can also be reproduced with the _CrossWorkgroup_ and _Workgroup_ storage classes (i.e. using global and local variables, respectively). I am unsure whether this issue is applicable to the _Generic_ and _Input_ storage classes.

This appears to relate to the _OpEntryPoint_ instruction, which prior to SPIR-V 1.4 had an _Interface_ variable list that was limited to variables of the _Input_ and shader-specific _Output_ storage classes only (and so excluding the _UniformConstant_ storage class, for example). In SPIR-V 1.4 and later, variables of all storage classes must be included in _Interface_.

In the generated SPIR-V for the example above, the _Interface_ of the _OpEntryPoint_ instruction was empty.

Approximately 5850 out of 50,000 SPIR-V files generated from the OpenCL Conformance Test Suite reproduced this validation failure.

**Comment by StuartDBrady** [comment]
Note, this was originally reported as issue #1205, but it turns out to be a more general problem than initially described. The use of OpenCL C code blocks is one specific case of this, which is affected because of the use of "block literal" globals in the implementation of OpenCL C code blocks. Once interface variables are correctly listed, the problem should be resolved for OpenCL C code blocks too with no further action needed.

I don't have any particular suggestions as to how this should be resolved, other than to say that it would seem to require an analysis pass to walk the call graph of LLVM functions as part of the translation.

It's not clear to me what the Interface list should contain for functions that call externally defined functions. How is it possible to know all of the globals used by an external function? Is this even required?

**Comment by AlexeySotkin** [comment]
Why do we need to list all global variables in entry point's interface in the first place? Do we need it for shaders only?
I also raised this concern in the original issue here https://github.com/KhronosGroup/SPIRV-Headers/issues/35#issuecomment-924733955
