### ISSUE TITLE
Generated SPIRV includes OpVariable initializers for Workgroup storage class 

### ISSUE THREAD

**Issue by llandwerlin-intel** [KhronosGroup/SPIRV-LLVM-Translator#1224]
The following OpenCL code : 
```
struct DummyStruct {
   uint a;
};

kernel void
test(global struct DummyStruct *a_ptr)
{
   local struct DummyStruct a_s;

   a_ptr->a = a_s.a;
}
```

Will generate this : 
```
         %74 = OpUndef %uint
         %83 = OpConstantComposite %struct_DummyStruct %74
   %test_a_s = OpVariable %_ptr_Workgroup_struct_DummyStruct Workgroup %83
```

This is a bit unexpected as OpenCL defines `local` variables as not initialized (https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/local.html)

Since the initializer is `OpUndef`, why not just completely drop it from the generated SPIRV?

**Comment by karolherbst** [comment]
SPIR-V is SSA so every value needs to be assigned prior use.

**Comment by llandwerlin-intel** [comment]
Fair.
