### ISSUE TITLE
Create a release branch for LLVM 8.0 support

### ISSUE THREAD

**Issue by pierremoreau** [KhronosGroup/SPIRV-LLVM-Translator#124]
Please create a _llvm_release_80 branch_.

**Comment by tjaalton** [comment]
yes please

Debian needs that

**Comment by tjaalton** [comment]
many thanks for creating the branch and tagging a new release, I've uploaded it to Debian

this can now be closed!

**Comment by AlexeySotkin** [comment]
Please note, this is a **pre**-release. The final release will be tagged around 1 month after llvm 8 official release.

**Comment by tjaalton** [comment]
sure, but why tag it to look like a final release (8.0.0-1)?

btw, I filed another ticket about that '-1' in the tag, it's just confusing downstream packagers and should be left out IMO

**Comment by AlexeySotkin** [comment]
The release is explicitly marked as pre-release, and the name states that it is for qualification branch of llvm - 8, which is also kind of pre-release branch yet.
I agree that tag may look confusing. Probably I should rename it to `pre-8.0.0`
The '-1' denotes version of the translator compatible with given version of llvm, in case we want to have multiple releases of translator based on llvm 8. We don't touch all 3 digits of the llvm version to know what exactly version of llvm should be used with this particular version of the translator.
BTW what did you mean by "uploaded to Debian" ?

**Comment by tjaalton** [comment]
I packaged it and uploaded to Debian (Linux), as part of the task of getting compute-runtime packaged
