### ISSUE TITLE
OCL21ToSPIRV.cpp uses language version wrong

### ISSUE THREAD

**Issue by airlied** [KhronosGroup/SPIRV-LLVM-Translator#128]
I've asked internally at Khronos and was told the source language version in SPIRV for C++ is meant to be 1.0 and isn't the CL version (2.1).

OCL21ToSPIRV::runOnModule checks for CLVer = std::get<1>(Src) which is incorrect.

Should it just check == 10000 or should the check just be removed?

**Comment by pierremoreau** [comment]
Agreed, the current check is wrong and could be dropped IMHO.

`CLVer` should also be renamed to avoid any confusion.

**Comment by AlexeySachkov** [comment]
I've removed this pass completely in #766, so I will close this issue as it doesn't seem to be relevant anymore
