### ISSUE TITLE
Should the mangler library be isolated?

### ISSUE THREAD

**Issue by pierremoreau** [KhronosGroup/SPIRV-LLVM-Translator#13]
In #11 we discussed that the mangler (found in “lib/SPIRV/Mangler”) is not part of the SPIR-V code per se, and could already be found in https://github.com/KhronosGroup/SPIR-Tools. 

The mangler should probably be moved out of “lib/SPIRV” to make it clearer that it is not part of the SPIR-V codebase. It could be moved to “lib”, or maybe spun into its separate repository which would then be used in this one as a library or a submodule.

**Comment by neildhickey** [comment]
Hi Pierre. Would it be possible for you to enumerate the benefits you see of separating out the Mangler into a separate repository?

**Comment by pierremoreau** [comment]
1. It would make it clear that it is not part of the SPIR-V <-> LLVM translator, but that it is only a dependency.
2. As it is also used in at least another project (SPIR-Tools), if the mangler needs to be updated, it easily benefits all its consumers without having to send the same fixes to all of them.

I don’t really see more benefits than those.

**Comment by AnastasiaStulova** [comment]
OpenCL TSG call July 31:
- Ok to do if we find a use case for this other than the translator itself.

**Comment by AnastasiaStulova** [comment]
@pierremoreau do you have any known use case for the mangler (other than the translator itself)?

**Comment by pierremoreau** [comment]
@AnastasiaStulova Not really; the mangler is also being used by SPIR-Tools, but I am not sure how used that tool is.

So we should probably just move it out of lib/SPIRV (maybe into lib/Mangler) but keep it in the same directory.

**Comment by thewilsonator** [comment]
The builtins should be intrinsics, not itanium with extensions mangled C++, it makes it much harder to work with non-C++ front ends.

**Comment by neildhickey** [comment]
@thewilsonator, this is a separate issue to the one being discussed here. If you would like to raise a separate issue we can discuss this in more detail.
For this particular issue, this project is the only project currently using the mangler library so we do not plan to carry out this refactoring work unless there is a clear need.
