### ISSUE TITLE
Unify the version numbers used throughout the project

### ISSUE THREAD

**Issue by pierremoreau** [KhronosGroup/SPIRV-LLVM-Translator#131]
* The project is exposed as version `0.2.1` via pkg-config (see in [CMakeLists.txt](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/master/CMakeLists.txt#L3));
* New releases are tagged as `$LLVM_VERSION-$iteration`; latest release is 8.0.0-1
* `llvm-spirv --version` returns the LLVM version (same as the release tags, but without the `-1` suffix);
* The version of the tool stored in the SPIR-V binary ([in the lower 16 bits of word 2](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#_a_id_physicallayout_a_physical_layout_of_a_spir_v_module_and_instruction) of the SPIR-V header), is stuck to [14](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/master/lib/SPIRV/SPIRVInternal.h#L65). Maybe this one doesn’t need to match the other versions though.

**Comment by AlexeySotkin** [comment]
Conclusion of the discussion of this issue on OpenCL tooling call was that using version from the **second bullet** everywhere should be fine.
The fourth bullet was not discussed though.
