### ISSUE TITLE
Need to update for an upstream API change in llvm

### ISSUE THREAD

**Issue by hokein** [KhronosGroup/SPIRV-LLVM-Translator#1408]
The deprecated llvm::PointerType::getElementType() is removed in LLVM upstream (https://github.com/llvm/llvm-project/commit/d593cf79458a59d37e75c886a4fc3ac6a02b484d).

**Comment by svenvh** [comment]
I believe this should have been addressed by #1386 already?  But please reopen if you are aware of any remaining uses.

**Comment by hokein** [comment]
oh, you're right, sorry, I didn't notice that.
