### ISSUE TITLE
SPIRV-LLVM-Translator does not build and install `spirv-llvm`

### ISSUE THREAD

**Issue by Nuc1eoN** [KhronosGroup/SPIRV-LLVM-Translator#1423]
Hi, I am building SPIRV-LLVM-Translator with:
```
        -DCMAKE_BUILD_TYPE=Release
        -DBUILD_SHARED_LIBS=ON
        -DCMAKE_INSTALL_PREFIX=/usr
        -DLLVM_INCLUDE_TESTS=OFF
```
But after the build is finished `llvm-spirv` has not been build under `_build/tools/llvm-spirv/`.

What could be the issue?

Here is the build log: https://gist.github.com/Nuc1eoN/09843137a445592c4a62b08474ecb9d7

**Comment by svenvh** [comment]
The default target to build/install is `LLVMSPIRVLib` I believe.  If you want `llvm-spirv` you need to explicitly request it (using e.g. `make llvm-spirv`).

**Comment by Nuc1eoN** [comment]
I am trying to package it for my distro and I have looked at archs PKGBUILD, they do not seem to do anything special? https://github.com/archlinux/svntogit-community/blob/packages/spirv-llvm-translator/trunk/PKGBUILD

It would be a lot easier to package, if it could be passed down as a compile flag to cmake.

**Comment by Nuc1eoN** [comment]
Ok I did it, I needed to pass `-DLLVM_BUILD_TOOLS=ON`
