### ISSUE TITLE
Please update llvm-spriv to a newer LLVM version: builds of LLVM's libclc fail with "Explicit load/store type does not match pointee type of pointer operand (Producer: 'LLVM15.0.0' Reader: 'LLVM 13.0.1')"

### ISSUE THREAD

**Issue by TheRealCuran** [KhronosGroup/SPIRV-LLVM-Translator#1467]
I recently opened llvm/llvm-project#54979 because LLVM's official libclc builds (Debian packages) started to lack the actual headers and bytecode files. The maintainer explained, that he is getting the following error:
> Explicit load/store type does not match pointee type of pointer operand (Producer: 'LLVM15.0.0' Reader: 'LLVM 13.0.1')

I first assumed that the Opaque Pointers might be the culprit after seeing e1d70a3f0382e8391acfa503ea2a89f81f132a0f but adding `-Xclang -no-opaque-pointers` didn't yield any changes.

Could you maybe update `llvm-spirv` to be based on a newer LLVM version in order to unblock the libclc builds for current snapshot versions of LLVM 15? Thank you! (If there is a backportable workaround for `llvm-spirv` please point us in the right direction.)

**Comment by svenvh** [comment]
> Could you maybe update llvm-spirv to be based on a newer LLVM version in order to unblock the libclc builds for current snapshot versions of LLVM 15?

We aim to keep the `master` branch of this repository in sync with LLVM's `main` branch and as far as I am aware we are pretty much up to date at the moment.

> Reader: 'LLVM 13.0.1'

I wonder where that comes from?  This suggests you're not using `llvm-spirv` from the `master` branch, but from the `llvm_release_130` branch.  That will not work nicely with LLVM `main`.

**Comment by TheRealCuran** [comment]
Yeah, that build is using the latest released `llvm-spirv` (which is, as far as I know build on LLVM 13).

But from your reply I gather that it's basically luck that any release would work against LLVM's `main`. Hm, that is going to be trickier to solve then for the packaging for apt.llvm.org. Anyway: thanks! I think I can close this issue then. Sorry for the noise.
