### ISSUE TITLE
RFE: please make new 14.0.0 release

### ISSUE THREAD

**Issue by kloczek** [KhronosGroup/SPIRV-LLVM-Translator#1468]
It would be good to have `SPIRV-LLVM-Translator` version synced with LLVM 14.0.0 and spirv-headers 1.3.211.0.

**Comment by kloczek** [comment]
Currently trying to rebuild 13.0.0 cmake fails with:
```console
-- Using SPIR-V Headers from
          /usr/include/spirv/1.2/
-- The CXX compiler identification is GNU 12.0.1
-- The C compiler identification is GNU 12.0.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:74 (find_package):
  Could not find a configuration file for package "LLVM" that is compatible
  with requested version "13.0.0".

  The following configuration files were considered but not accepted:

    /usr/lib64/cmake/llvm/LLVMConfig.cmake, version: 14.0.0
    /lib64/cmake/llvm/LLVMConfig.cmake, version: 14.0.0
```

**Comment by svenvh** [comment]
I have created a [new release](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/releases/tag/v14.0.0) from the `llvm_release_140` branch.

> and spirv-headers 1.3.211.0.

We don't really follow releases for SPIRV-Headers, but instead rely on the commit specified in `spirv-headers-tag.conf`.  cmake should fetch the correct revision automatically, but please let us know if this is problematic.

**Comment by kloczek** [comment]
> I have created a [new release](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/releases/tag/v14.0.0) from the `llvm_release_140` branch.

Thank you tested and looks like it works 😄
