### ISSUE TITLE
error: ‘class llvm::CallInst’ has no member named ‘getParamStructRetType’

### ISSUE THREAD

**Issue by jiapei100** [KhronosGroup/SPIRV-LLVM-Translator#1475]
[https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/master/lib/SPIRV/SPIRVWriter.cpp](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/master/lib/SPIRV/SPIRVWriter.cpp)

line 4680, 4771,4848,4953 : 4 occurences of **getParamStructRetType**, which is **NOT** for **llvm::CallInst**.

I believe this is a bug, but can anybody help to fix it?

Thank you ...

**Comment by svenvh** [comment]
As far as I can see, `llvm::CallBase` defines this method in [InstrTypes.h](https://github.com/llvm/llvm-project/blob/b6388e4a0050fa248f774f5dacfa3e566e8daef1/llvm/include/llvm/IR/InstrTypes.h#L1778)

Are you using the `main` branch of llvm when trying to build llvm-spirv?

**Comment by jiapei100** [comment]
@svenvh 
You are right. I'm using **LLVM** grabbed from the repository directly. I'm using **Ubuntu 22.04**, it's the newest **LLVM** from repo. version 11.4.

1. That is to say, I'm **NOT** using **LLVM** `main` branch, but the branch `14.x`. As you can see from
[https://github.com/llvm/llvm-project/blob/release/14.x/llvm/include/llvm/IR/InstrTypes.h](https://github.com/llvm/llvm-project/blob/release/14.x/llvm/include/llvm/IR/InstrTypes.h), there is nothing related to **getParamStructRetType** there.

2. And I was thinking [https://github.com/KhronosGroup/SPIRV-LLVM-Translator/tree/llvm_release_140](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/tree/llvm_release_140) is corresponding to **LLVM 14.x**. Unfortunately, it does **NOT**... 

So, is there anything of **SPIRV-LLVM** related to **LLVM 14.x**??

Thank you ...

**Comment by svenvh** [comment]
> So, is there anything of SPIRV-LLVM related to LLVM 14.x??

The `llvm_release_140` branch should work with LLVM 14.x.  As far as I can see, there is no occurrence of `getParamStructType` in SPIRVWriter.cpp on the llvm_release_140 branch: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/llvm_release_140/lib/SPIRV/SPIRVWriter.cpp

(in your first message you linked to the `master` branch; are you sure you have the `llvm_release_140` branch checked out?)

**Comment by jiapei100** [comment]
@svenvh 
Yeah you are absolutely correct...  More or less, it's still a kind of weird to me...

- I use this way to check out the branch **llvm_release_140**.

```console
➜  Downloads git clone https://github.com/KhronosGroup/SPIRV-LLVM-Translator                      
Cloning into 'SPIRV-LLVM-Translator'...
remote: Enumerating objects: 22475, done.
remote: Counting objects: 100% (511/511), done.
remote: Compressing objects: 100% (276/276), done.
remote: Total 22475 (delta 245), reused 396 (delta 183), pack-reused 21964
Receiving objects: 100% (22475/22475), 10.43 MiB | 7.08 MiB/s, done.
Resolving deltas: 100% (16506/16506), done.
➜  Downloads cd SPIRV-LLVM-Translator 
➜  SPIRV-LLVM-Translator git:(master) git checkout -b llvm_release_140
Switched to a new branch 'llvm_release_140'
➜  SPIRV-LLVM-Translator git:(llvm_release_140) ls ./lib/SPIRV/SPIRVWriter.cpp
./lib/SPIRV/SPIRVWriter.cpp
➜  SPIRV-LLVM-Translator git:(llvm_release_140) grep -rwn "getParamStructRetType"
lib/SPIRV/SPIRVWriter.cpp:4680:      ResTy = CI->getParamStructRetType(0);
lib/SPIRV/SPIRVWriter.cpp:4771:      ResTy = CI->getParamStructRetType(0);
lib/SPIRV/SPIRVWriter.cpp:4848:      ResTy = CI->getParamStructRetType(0);
lib/SPIRV/SPIRVWriter.cpp:4953:        SPRetTy = transType(F->getParamStructRetType(0));
lib/SPIRV/SPIRVRegularizeLLVM.cpp:353:  StructType *SRetTy = cast<StructType>(Attrs.getParamStructRetType(0));
lib/SPIRV/SPIRVRegularizeLLVM.cpp:398:      auto *SRetTy = F.getParamStructRetType(0);
```


- If I checked the branch directory as follows:
```console
➜  ~ git clone -b llvm_release_140 https://github.com/KhronosGroup/SPIRV-LLVM-Translator SPIRV-LLVM-Translator
Cloning into 'SPIRV-LLVM-Translator'...
remote: Enumerating objects: 22475, done.
remote: Counting objects: 100% (511/511), done.
remote: Compressing objects: 100% (277/277), done.
remote: Total 22475 (delta 245), reused 395 (delta 182), pack-reused 21964
Receiving objects: 100% (22475/22475), 10.57 MiB | 1.10 MiB/s, done.
Resolving deltas: 100% (16486/16486), done.
➜  ~ cd SPIRV-LLVM-Translator
➜  SPIRV-LLVM-Translator git:(llvm_release_140) ls ./lib/SPIRV/SPIRVWriter.cpp
./lib/SPIRV/SPIRVWriter.cpp
➜  SPIRV-LLVM-Translator git:(llvm_release_140) grep -rwn "getParamStructRetType"
➜  SPIRV-LLVM-Translator git:(llvm_release_140) 
```



It seems for the design of **SPIRV-LLVM-Translator**, `git checkout -b` **won't be able to** check out the right branch??? That's ..... hmmmm

Anyway, thank you, I now use the 2nd way to checkout the **llvm_release_140** branch directly... And it's built...

**Comment by AlexeySachkov** [comment]
@jiapei100, 'git checkout -b' command creates a new branch instead of using existing one. You need to omit '-b' to get it work as you expect
