### ISSUE TITLE
Build break on llvm_release_130 on OpControlBarrierArriveINTEL

### ISSUE THREAD

**Issue by mnaczk** [KhronosGroup/SPIRV-LLVM-Translator#1485]
Build break SPIRV-LLVM-Translator llvm_release_130:
error: 'OpControlBarrierArriveINTEL' was not declared in this scope

Reason:
Too old SPIRV-Headers

Fixes proposals:
First:
Need to update hash in https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/llvm_release_130/spirv-headers-tag.conf to latest tag "sdk-1.3.211.0"

Second:
Fix https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/llvm_release_130/CMakeLists.txt#L19
Now when LLVM_TOOL_SPIRV_HEADERS_BUILD and LLVM_EXTERNAL_SPIRV_HEADERS_SOURCE_DIR are not defined
SPIRV-Headers is downloaded and built, thanks to the command 
FetchContent_MakeAvailable(spirv-headers) https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/llvm_release_130/CMakeLists.txt#L37

But if LLVM_TOOL_SPIRV_HEADERS_BUILD or LLVM_EXTERNAL_SPIRV_HEADERS_SOURCE_DIR are defined SPIRV-Headers is only added as an include directory to LLVMSPIRVLib https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/llvm_release_130/lib/SPIRV/CMakeLists.txt#L58

This causes build break 
lib/SPIRV/libSPIRV/SPIRVOpCode.h:44:10: fatal error: spirv/unified1/spirv.hpp: No such file or directory

**Comment by YetAnotherCompilerEngineer** [comment]
I don't see OpControlBarrierArriveINTEL be emitted by this version of SPIR-V generator. Also SPIR-V consumer of the translator can not consume this instruction, so I'd suggest to upstream it here first.
