### ISSUE TITLE
Changes to the installed header file

### ISSUE THREAD

**Issue by pierremoreau** [KhronosGroup/SPIRV-LLVM-Translator#15]
1. Should we install it in a prefix or keep it directly under “include”?
    I was initially pushing for installing it in a prefix, but since it’s a single header file, it doesn’t seem that useful.

2. Should we rename the installed header file? “SPIRV.h” a) seems too generic, and b) could easily be confused for one of the SPIR-V header files, which it is not. We should probably rename it to “LLVMSPIRVLib.h”, to match the library name.

**Comment by karolherbst** [comment]
1. yeah, I think we could put it under llvm/ or llvm-spirv/ or something.
2. sounds good.

**Comment by tomeuv** [comment]
1. don't know
2. sounds good
