### ISSUE TITLE
Update tests containing unsupported constant expressions

### ISSUE THREAD

**Issue by svenvh** [KhronosGroup/SPIRV-LLVM-Translator#1548]
LLVM is removing most constant expressions, see https://discourse.llvm.org/t/rfc-remove-most-constant-expressions/63179 , which is causing some test failures.  For now, failing tests have been XFAILed:

- https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1544
- https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1547

cc: @bader @asudarsa

**Comment by MrSidims** [comment]
@vmaksimo could I please ask you to take a look at this and update/remove the tests when you have time

**Comment by MrSidims** [comment]
Fixed by https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1644
