### ISSUE TITLE
incorrect translation of sampler/image kernel arguments

### ISSUE THREAD

**Issue by franz** [KhronosGroup/SPIRV-LLVM-Translator#1562]
I have bitcode ( [sample.ll.gz](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/files/9220700/sample.ll.gz) ) with a function that forwards image+sampler arguments to another, and is correctly translated to SPIR-V by the `llvm_release_140` branch but incorrectly by the main (@ 70ebd9b82edb5d8aca04a3e8bbc) branch.

```llvm
%opencl.image2d_ro_t = type opaque
%opencl.sampler_t = type opaque
....

; Function Attrs: convergent mustprogress norecurse nounwind
define hidden spir_kernel void @_Z11tex2DKernelPfP13__hip_textureii(float addrspace(1)* nocapture noundef writeonly %0, %opencl.image2d_ro_t addrspace(1)* %1, %opencl.sampler_t addrspace(2)* %2, i32 noundef %3, i32 noundef %4) local_unnamed_addr #5
```

translated with llvm 14 branch:

```
....
         %20 = OpTypeImage %void 2D 0 0 0 0 Unknown ReadOnly
         %21 = OpTypeSampler
....
%_Z11tex2DKernelPfP13__hip_textureii = OpFunction %void None %61
         %63 = OpFunctionParameter %_ptr_CrossWorkgroup_float
         %64 = OpFunctionParameter %20
         %65 = OpFunctionParameter %21
         %66 = OpFunctionParameter %uint
         %67 = OpFunctionParameter %uint
....
```

translated with main branch:

```
....
         %20 = OpTypeImage %void 2D 0 0 0 0 Unknown ReadOnly
         %21 = OpTypeSampler
....
%_Z11tex2DKernelPfP13__hip_textureii = OpFunction %void None %61
         %63 = OpFunctionParameter %_ptr_CrossWorkgroup_float
         %64 = OpFunctionParameter %21
         %65 = OpFunctionParameter %21
         %66 = OpFunctionParameter %uint
         %67 = OpFunctionParameter %uint
...
```

The 2nd argument ends up being sampler instead of image. It also fails validation:

```
error: line 187: OpFunctionCall Argument <id> '64[%64]'s type does not match Function <id> '20[%20]'s parameter type.
  %100 = OpFunctionCall %v4float %_chip_tex2df_impl %64 %65 %99
```

**Comment by svenvh** [comment]
> and is correctly translated to SPIR-V by the llvm_release_140 branch

Do you also have the SHA-1 of the llvm_release_140 commit you are using?  I've just tried on 9629514b517d2c77be7e5f31cda438c2679918e3 and that seems to produce the same (invalid) SPIR-V as the `main` branch.

**Comment by svenvh** [comment]
A quick bisection tells that 2968e1672e6319f900f7f6222e3e6c79f2ddfca5 is the first bad commit.

@jcranmer-intel would you be able to have a look at this?
