### ISSUE TITLE
crash with latest clang and opaque pointers

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/SPIRV-LLVM-Translator#1624]
My script to compile OpenCL C kernels started to produce a crash in the SPIR-V LLVM Translator recently (with the latest Clang and SPIR-V LLVM Translator as of yesterday).  Here is my kernel:

```c
__kernel void test(write_only image2d_t img)
{
    int2 coord = (int2)((int)get_global_id(0), (int)get_global_id(1));
    int4 data = 1;

    write_imagei(img, coord, data);
}
```

Here is how I am compiling to SPIR-V:

```sh
>clang -c -fcolor-diagnostics -cl-std=CL1.2 -target spir64 -emit-llvm -Xclang -finclude-default-header -g0 -O3 ..\..\..\test_kernels\write_image_2d.cl

>llvm-spirv write_image_2d.bc -o write_image_2d.spv --spirv-ext=+all
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: llvm-spirv write_image_2d.bc -o write_image_2d.spv --spirv-ext=+all
Exception Code: 0xC0000005
 #0 0x00007ff6aa2d0f1c SPIRV::toTypedPointerType D:\git\spirv-llvm-translator\llvm\projects\SPIRV-LLVM-Translator\lib\SPIRV\SPIRVUtil.cpp:924:0
 #1 0x00007ff6aa2d22e6 std::vector<SPIRV::BuiltinArgTypeMangleInfo,std::allocator<SPIRV::BuiltinArgTypeMangleInfo> >::size C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include\vector:1549:0
 #2 0x00007ff6aa2d22e6 SPIRV::BuiltinFuncMangleInfo::getTypeMangleInfo D:\git\spirv-llvm-translator\llvm\projects\SPIRV-LLVM-Translator\lib\SPIRV\SPIRVInternal.h:510:0
 #3 0x00007ff6aa2d22e6 SPIRV::typeMangle D:\git\spirv-llvm-translator\llvm\projects\SPIRV-LLVM-Translator\lib\SPIRV\SPIRVUtil.cpp:936:0
 #4 0x00007ff6aa2bb426 std::basic_string<char,std::char_traits<char>,std::allocator<char> >::data C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include\xstring:3926:0
 #5 0x00007ff6aa2bb426 llvm::StringRef::{ctor} D:\git\spirv-llvm-translator\llvm\include\llvm\ADT\StringRef.h:101:0
 #6 0x00007ff6aa2bb426 SPIRV::mutateCallInst(class llvm::Module *, class llvm::CallInst *, class std::function<(class llvm::CallInst *, class std::vector<class llvm::Value *, class std::allocator<class llvm::Value *>> &)>, class SPIRV::BuiltinFuncMangleInfo *, class llvm::AttributeList *, bool) D:\git\spirv-llvm-translator\llvm\projects\SPIRV-LLVM-Translator\lib\SPIRV\SPIRVUtil.cpp:955:0
 #7 0x00007ff6aa2bbc47 std::vector<SPIRV::BuiltinArgTypeMangleInfo,std::allocator<SPIRV::BuiltinArgTypeMangleInfo> >::_Tidy C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include\vector:1765:0
 #8 0x00007ff6aa2bbc47 std::vector<SPIRV::BuiltinArgTypeMangleInfo,std::allocator<SPIRV::BuiltinArgTypeMangleInfo> >::{dtor} C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include\vector:712:0
...
```

With some help from @bader we traced this to use of opaque pointers in Clang.  A small update to the clang command line fixes the problem (note: `-Xclang -no-opaque-pointers`):

```sh
>clang -c -fcolor-diagnostics -cl-std=CL1.2 -target spir64 -emit-llvm -Xclang -finclude-default-header -Xclang -no-opaque-pointers -g0 -O3 ..\..\..\test_kernels\write_image_2d.cl
```

Is this expected behavior?  Is there something we could or should be doing in the SPIR-V LLVM Translator to "fix" this?

If nothing else, this issue may be useful to anyone else experiencing a similar issue.  Thanks!

**Comment by MrSidims** [comment]
No, it's not expected.
What is happening is that here the translator while processing `tail call spir_func void @_Z12write_imagei14ocl_image2d_woDv2_iDv4_i(ptr addrspace(1) %0, <2 x i32> noundef %6, <4 x i32> noundef <i32 1, i32 1, i32 1, i32 1>)` is considering image argument as a typed pointer argument and asserts out, when find, that it's not typed.

**Comment by MrSidims** [comment]
@bashbaug I've just trying to translate the example with https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1613 applied and it works. So I assume when we merge all [Mutator] patches the issue shoud be gone.

**Comment by bader** [comment]
@MrSidims, did you use clang from https://github.com/llvm/llvm-project or https://github.com/intel/llvm? Note: the issue doesn't reproduce with the clang built from https://github.com/intel/llvm sources because opaque pointers are disabled by default in that repository.

**Comment by MrSidims** [comment]
@bader I'm using https://github.com/llvm/llvm-project to test the translator.

**Comment by MrSidims** [comment]
The example above is now being successfully translated on my side.

**Comment by bashbaug** [comment]
Thanks!  I can confirm the latest llvm-spirv is working on my end, too.
