### ISSUE TITLE
InvalidInstruction: Can't translate llvm instruction: freeze

### ISSUE THREAD

**Issue by biggysmith** [KhronosGroup/SPIRV-LLVM-Translator#1626]
Hi all,

I'm experimenting with OpenCL compilation and I'm getting the following error, when using llvm-spirv (release 15):

```
InvalidInstruction: Can't translate llvm instruction:
1>   %67 = freeze <4 x i1> %66 
```

I use the following commands:

clang -target spirv64 -emit-llvm -cl-std=clc++2021-O2 -c -o broken_mpr.bc broken_mpr.clcpp
llvm-spirv -spirv-max-version=1.2 -o broken_mpr.spv broken_mpr.bc

I should add this only happens when I call clang with -O2, so I assume this is some sort of optimisation error.

I've attached the .bc file I've been trying to translate

[broken_mpr.zip](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/files/9639119/broken_mpr.zip)

**Comment by svenvh** [comment]
Thanks for the report, this is a known issue indeed, see #1140.

> I should add this only happens when I call clang with -O2, so I assume this is some sort of optimisation error.

LLVM's optimizations may introduce `freeze` instructions, and llvm-spirv does not handle them yet as there is no direct SPIR-V counterpart.  Until llvm-spirv supports it, you could try with a lower optimization level, apply the llvm-spirv workaround suggested in #1140, or try to figure out what part of the kernel code triggers the creation of the offending `freeze` (and then rewrite the kernel to avoid that if possible).

**Comment by biggysmith** [comment]
ah I see.  My kernel does indeed work with -O1.

May I ask what exactly the freeze instructions does?  Is there a resource somewhere that lists these instructions?

**Comment by svenvh** [comment]
All LLVM instructions are documented in the Language Reference Manual; see [here](https://llvm.org/docs/LangRef.html#freeze-instruction) for the freeze instruction.
