### ISSUE TITLE
Release for LLVM-8

### ISSUE THREAD

**Issue by dvrogozh** [KhronosGroup/SPIRV-LLVM-Translator#164]
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/releases/tag/v8.0.0-1 is classified as Pre-Release. I guess that's because LLVM-8 was not yet out on the moment of tagging, but it is now. Can v8.0.0-1 be promoted to official release? or release against LLVM-8 issues if any changes/updates are needed?

**Comment by AlexeySotkin** [comment]
I have promoted it to release. Thanks.

**Comment by dvrogozh** [comment]
Thank you. Can be closed now I think.
