### ISSUE TITLE
subgroup ballot requiring a too high SPIR-V version?

### ISSUE THREAD

**Issue by pjaaskel** [KhronosGroup/SPIRV-LLVM-Translator#1736]
Currently the translator requires v1.3 when OpenCL subgroup_ballot is used. I'm not sure that's correct. Intel's OpenCL driver specifically advertises the `cl_khr_subgroup_ballot`extension which [should imply SPIR-V support:](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_Env.html#_cl_khr_subgroup_ballot) "If the OpenCL environment supports the extension cl_khr_subgroup_ballot, then the environment must accept SPIR-V modules that declare the following SPIR-V capabilities...". However, the driver only supports SPIR-V 1.2, thus making it not possible to use the extension.

This is introduced in 0c2ade64300 by @bashbaug. When I lowered the required SPIR-V version to v1.2 the driver didn't complain about the kernel that called subgroup_ballot(). What's going on here?

**Comment by AlexeySachkov** [comment]
Hi @pjaaskel,

[`OpGroupNonUniformBallot`](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpGroupNonUniformBallot) is missing in SPIR-V before 1.3. Therefore, I would say that it is correct for the translator to emit 1.3 version when this instruction is used.

It seems like OpenCL environment spec implicitly implies that consume should either officially support 1.3 in full, or it should be more flexible and support 1.3, but only if `GroupNonUniformBallot` capability is declared and no other 1.3 capabilities/instructions are used.

**Comment by pjaaskel** [comment]
Thanks, for some reason I overlooked that spec. Opened [here](https://github.com/intel/compute-runtime/issues/585) instead.
