### ISSUE TITLE
create a branch for llvm16

### ISSUE THREAD

**Issue by tjaalton** [KhronosGroup/SPIRV-LLVM-Translator#1860]
llvm 16 is about to be released, and there still isn't a branch for it?

**Comment by svenvh** [comment]
I've now created the [llvm_release_160](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/tree/llvm_release_160) branch.

**Comment by tjaalton** [comment]
thanks!

**Comment by MehdiChinoune** [comment]
Could you create v16.0.0 tag.

**Comment by svenvh** [comment]
Done.
