### ISSUE TITLE
oclIsBuiltin needs rework

### ISSUE THREAD

**Issue by Naghasan** [KhronosGroup/SPIRV-LLVM-Translator#19]
The function `oclIsBuiltin` is suppose to check if the given function name is an OpenCL built-in.

The function is obviously wrong as it will return true for any function that is mangled (starts with `_Z`).

This is causing issues when converting C++ based applications for OpenCL (like SYCL).

**Comment by bader** [comment]
@Naghasan oclIsBuiltin is used during the translation of LLVM IR generated from OpenCL C. It's safe to assume that mangled functions are built-in function in this context.

For OpenCL C++ or other languages "SPIR-V friendly LLVM IR" is supposed to be used.
Translator will not use this function for translating "[SPIR-V friendly LLVM IR](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/master/docs/SPIRVRepresentationInLLVM.rst)" to SPIR-V.

**Comment by AlexeySachkov** [comment]
Based on comment from @bader, I will close this in favor of #206, which aims to find some universal stable representation of SPIR-V in LLVM IR, which can be used by different front-ends which are interested to be producing SPIR-V
