### ISSUE TITLE
[llvm_release_170] A build errors

### ISSUE THREAD

**Issue by Kerrung** [KhronosGroup/SPIRV-LLVM-Translator#2172]
OS: Arch Linux
LLVM version: 17
[A log file](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/files/12818382/log.txt)
[PKGBUILD](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/files/12818388/PKGBUILD.zip)
[makepkg.conf](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/files/12818452/makepkg.zip)
![image](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/assets/36989404/13f2ddef-5242-4044-966f-b71336b85cd2)

**Comment by MrSidims** [comment]
@Kerrung what is the version of [SPIR-V Headers](https://github.com/KhronosGroup/SPIRV-Headers) on the system?  If I read the log correctly `-- Using SPIR-V Headers from          /usr/include/spirv/` the tag from spirv-headers-tag.conf is ignored

**Comment by Kerrung** [comment]
> @Kerrung what is the version of [SPIR-V Headers](https://github.com/KhronosGroup/SPIRV-Headers) on the system? If I read the log correctly `-- Using SPIR-V Headers from /usr/include/spirv/` the tag from spirv-headers-tag.conf is ignored

![image](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/assets/36989404/0818741b-53a7-479b-9862-5b74621ead66)
https://archlinux.org/packages/extra/any/spirv-headers/
