### ISSUE TITLE
OpIAddCarry and OpISubBorrow aren't conformant with spec

### ISSUE THREAD

**Issue by bwlodarcz** [KhronosGroup/SPIRV-LLVM-Translator#2179]
#2167 and #2168 are merged to the mainline and aren't conformant with spec.
LLVM intrinsic (in both u{sub/add}.with.overflow) returns struct {SomeType, i1} and SPIRV standard expects from IAddCarry and ISubBorrow to return {SomeType, SomeType}.
When we can change types for instructions accordingly, the real problem is with the next instructions which are using second element of the struct e.g. 
`%1 = extractvalue i1 %0 1`.
Here i1 will be converted to BoolType which is incorrect - struct returning from IAddCarry or ISubBorrow have both elements of the same type.  
Potential workaround was tested here: [workaround](https://github.com/bwlodarcz/SPIRV-LLVM-Translator/tree/uadd_with_overflow_workaround).
It was based on emitting 5 instructions converting second type of struct to BoolType but it's highly inefficient and will be cause of bugs in future.
I'm opening this issue to have a discussion and potential track of progress what to do with this problem.

**Comment by MrSidims** [comment]
Should be fixed now
