### ISSUE TITLE
DWARFv5: static data members declarations are DW_TAG_variable

### ISSUE THREAD

**Issue by jsji** [KhronosGroup/SPIRV-LLVM-Translator#2224]
Clang/LLVM has implemented new DWARFv5 issue 161118.1  "DW_TAG for C++ static data members". 

https://github.com/llvm/llvm-project/pull/72234

https://github.com/llvm/llvm-project/pull/72235

We should update llvm-spirv to support it.

Currently, llvm-spirv will assert for the new LLVM IR.

!11 = !DIDerivedType(tag: DW_TAG_variable, name: "smem", scope: !12, file: !3, line: 4, baseType: !15, flags: DIFlagStaticMember)

**Comment by MrSidims** [comment]
@jsji thanks, what is the assert message?

**Comment by jsji** [comment]
See https://github.com/intel/llvm/actions/runs/6910146011/job/18803283913

 Unxpected debug info type for variable
# | UNREACHABLE executed at /__w/llvm/llvm/src/llvm-spirv/lib/SPIRV/LLVMToSPIRVDbgTran.cpp:362!

**Comment by jsji** [comment]
A workaround was implemented in https://github.com/intel/llvm/pull/11920/commits/3f8d7ed61ce0b2261f24d208a660580b32bb442c
