### ISSUE TITLE
trunk Fails to build from source error: ‘CapabilityLongConstantCompositeINTEL’ was not declared in this scope

### ISSUE THREAD

**Issue by LW-archlinux** [KhronosGroup/SPIRV-LLVM-Translator#2261]
spirv-llvm-translator trunk

https://github.com/KhronosGroup/SPIRV-Headers/commit/d5acd42cb7cdaa5d0f2c5f739208eeeed395f491 renamed several intel related things.

This breaks build of spirv-llvm-translator trunk .

**Comment by svenvh** [comment]
I guess this will be fixed by https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2258 ?
cc: @MrSidims

**Comment by LW-archlinux** [comment]
yup, #2258 solves this.
