### ISSUE TITLE
Missing translation for OpIAddCarry, OpISubCarry, OpSMulExtended, OpUMulExtended

### ISSUE THREAD

**Issue by Snektron** [KhronosGroup/SPIRV-LLVM-Translator#2302]
It seems that the overflow family of instructions mentioned in the issue title are currently not being translated, and result in an error when attempting to use them.

**Comment by bwlodarcz** [comment]
OpIAddCarry and OpISubBorrow are currently implemented. OpSMulExtended and OpUMulExtended are not.

**Comment by Snektron** [comment]
Apologies, I did't see that the carry instructions were already implemented.

LLVMs smul.with.overflow intrinsic also returns a struct {T, i1}, so I guess that will be similarly annoying.

**Comment by vmaksimo** [comment]
@Snektron `MulExtended` instructions are supported now. Guess the issue can be closed

**Comment by Snektron** [comment]
Very nice, thank you!!
