### ISSUE TITLE
Lack of testing or unneeded code in SPIRVRegularizeLLVM

### ISSUE THREAD

**Issue by AlexeySachkov** [KhronosGroup/SPIRV-LLVM-Translator#232]
I've found that even if [SPIRVRegularizeLLVM.cpp:113](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/master/lib/SPIRV/SPIRVRegularizeLLVM.cpp#L113) line is commented out, no LIT tests fails. See #231

This means that we either don't have any tests for this function or this function is not needed anymore and can be safely removed.

**Comment by MrSidims** [comment]
The code no longer exists, closing
