### ISSUE TITLE
Please create an llvm_release_180 branch

### ISSUE THREAD

**Issue by berolinux** [KhronosGroup/SPIRV-LLVM-Translator#2342]
The current main branch has moved on to LLVM main (19), but there is no llvm_release_180 branch yet. Probably llvm_release_180 should be created from commit 8c357de0dde425eb7d46810b354d143b790caba2, or maybe from the current main branch with commit fd22f8e281d189d0d111228220ebad5e36628e22 reverted.

**Comment by svenvh** [comment]
I've just created the `llvm_release_180` branch from latest `main` with the LLVM version update commit reverted.  Its CI configuration will be updated by #2343

**Comment by MehdiChinoune** [comment]
LLVM-18 is at RC phase, will be released soon, any plan for releasing 18?
