### ISSUE TITLE
Linking fails if SPIRV-Tools is installed separately and found as a cmake package

### ISSUE THREAD

**Issue by manuelmohr** [KhronosGroup/SPIRV-LLVM-Translator#2358]
Linking fails if SPIRV-Tools is compiled first, installed, and found as a cmake package by SPIRV-LLVM-Translator.

I build both SPIRV-LLVM-Translator and SPIRV-Tools within a standard Ubuntu 22.04 environment.

The used versions are:
* LLVM 16.0.6 pre-installed
* SPIRV-LLVM-Translator v16.0.0
* SPIRV-Tools v2023.2

If I build and install SPIRV-Tools first, and try to build SPIRV-LLVM-Translator next, cmake will successfully find the SPIRV-Tools cmake package and set up include paths and linker flags appropriately. But the final link step will fail:

```
/usr/bin/ld: tools/llvm-spirv/CMakeFiles/llvm-spirv.dir/llvm-spirv.cpp.o: in function `main':
llvm-spirv.cpp:(.text.startup.main+0x2732): undefined reference to `spvtools::SpirvTools::SpirvTools(spv_target_env)'
/usr/bin/ld: llvm-spirv.cpp:(.text.startup.main+0x276d): undefined reference to `spvtools::SpirvTools::SetMessageConsumer(std::function<void (spv_message_level_t, char const*, spv_position_t const&, char const*)>)'
/usr/bin/ld: llvm-spirv.cpp:(.text.startup.main+0x28d6): undefined reference to `spvtools::SpirvTools::Disassemble(unsigned int const*, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, unsigned int) const'
/usr/bin/ld: llvm-spirv.cpp:(.text.startup.main+0x2961): undefined reference to `spvtools::SpirvTools::~SpirvTools()'
collect2: error: ld returned 1 exit status
```

After some investigation, I think this is because SPIRV-LLVM-Translator tries linking against `SPIRV-Tools-shared`, which has default-hidden symbol visibility, but SPIRV-LLVM-Translator references symbols that are regarded as private.  Hence, linking fails.

From my current understanding, only the symbols marked as `SPIRV_TOOLS_EXPORT` in https://github.com/KhronosGroup/SPIRV-Tools/blob/main/include/spirv-tools/libspirv.h are accessible when linking against `SPIRV-Tools-shared`, hence the current usage here seems wrong (and it should be `SPIRV-Tools-static` instead).

If I change the cmake config to link against `SPIRV-Tools-static` instead (which has full public symbol visibility), linking succeeds.

See also https://github.com/KhronosGroup/SPIRV-Tools/issues/3909 and https://github.com/KhronosGroup/SPIRV-Tools/blob/b7413609cf2d5adccc877d71a1d67ec43bea07c0/CMakeLists.txt#L162.

**Comment by svenvh** [comment]
Thanks for the report.  Until last year, this project's cmake configuration wasn't even considering `SPIRV-Tools-static`.  I've created backport https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2370 on top of the `llvm_release_160` branch; any chance you could give this a try to see if it fixes your issue?

**Comment by svenvh** [comment]
The unresolved symbols are part of the [SPIRV-Tools C++ API](https://github.com/KhronosGroup/SPIRV-Tools/blob/main/include/spirv-tools/libspirv.hpp).  What seems odd to me is that those don't have any symbol visibility markings (unlike the C API in `libspirv.h` as you pointed out), so they would indeed be hidden under `-fvisibility=hidden`.  Perhaps you can try sprinkling some `SPIRV_TOOLS_EXPORT` or  `__attribute__((visibility("default")))` into `libspirv.hpp` and see if that resolves the issue?

**Comment by svenvh** [comment]
Thanks for confirming the fix!  I have created https://github.com/KhronosGroup/SPIRV-Tools/pull/5591 to fix this in SPIRV-Tools.

**Comment by svenvh** [comment]
The SPIRV-Tools fix has just been merged, so closing this; but please reopen if you are still seeing issues.
