### ISSUE TITLE
SPIRVError.cpp misses #include "LLVMSPIRVLib.h"

### ISSUE THREAD

**Issue by anbe42** [KhronosGroup/SPIRV-LLVM-Translator#2376]
The prototype for `getErrorMessage()` is declared in `LLVMSPIRVLib.h`, the definition is in `SPIRVError.cpp`.
If I build with `-fvisibility=hidden` and some visibility "default" modifications (as described in #1963), this does not reach the compilation of `SPIRVError.cpp` since that does not include the header with the prototype.

Noticed in branch `llvm_release_180`, so it's probably in `main` as well. Not sure if older branches are affected.

**Comment by svenvh** [comment]
Thanks for reporting!  Does #2377 fix the issue for you?

**Comment by anbe42** [comment]
> Thanks for reporting! Does #2377 fix the issue for you?

Yes.
