### ISSUE TITLE
Release 18.0

### ISSUE THREAD

**Issue by MehdiChinoune** [KhronosGroup/SPIRV-LLVM-Translator#2414]
LLVM 18.1.0 is out, Maybe It's time to release a compatible spirv-llvm-translator.

**Comment by svenvh** [comment]
On it, thanks for the heads-up!

**Comment by svenvh** [comment]
Created https://github.com/KhronosGroup/SPIRV-LLVM-Translator/releases/tag/v18.1.0 .
