### ISSUE TITLE
llvm-as does not verify LLVM output from SPIR-V to LLVM translation (Overlapping tbaa.struct regions)

### ISSUE THREAD

**Issue by asudarsa** [KhronosGroup/SPIRV-LLVM-Translator#2467]
LLVM_SPIRV :: extensions/INTEL/SPV_INTEL_fpga_reg/IntelFPGAReg.ll test is failing in CI runs for the following PR (and few more recently):
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2466

Log:
/usr/lib/llvm-19/bin/llvm-as: assembly parsed, but does not verify as correct!
Overlapping tbaa.struct regions
  call void @llvm.memcpy.p0.p0.i64(ptr align 4 %agg-temp4, ptr align 4 %u1, i64 4, i1 false), !tbaa.struct !14
!14 = !{i64 0, i64 4, !9, i64 0, i64 4, !15}
Overlapping tbaa.struct regions
  call void @llvm.memcpy.p0.p0.i64(ptr align 4 %u2, ptr align 4 %ref.tmp3, i64 4, i1 false), !tbaa.struct !14
!14 = !{i64 0, i64 4, !9, i64 0, i64 4, !15}

**Comment by asudarsa** [comment]
Full log: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/actions/runs/8469459182/job/23204840432?pr=2466

**Comment by MrSidims** [comment]
Fixed
