### ISSUE TITLE
`ID '19' decorated with NoSignedWrap multiple times is not allowed.`

### ISSUE THREAD

**Issue by ben-clayton** [KhronosGroup/SPIRV-LLVM-Translator#2509]
With the latest Vulkan Validation Layers, the internal Google build / test is now failing with:

```
> spirv-val OpPhi_ArgumentsPlaceholders.ll

error: line 49: ID '19' decorated with NoSignedWrap multiple times is not allowed.
  %inc = OpIAdd %uint %j_0 %uint_1

Command failed: exit status 1
```

Note: The new no duplicate decorations validation has triggered for many other SPIR-V projects.

**Comment by svenvh** [comment]
All issues with duplicate decorations should now be fixed on the `main` branch.
