### ISSUE TITLE
Please create new v19.1.0 release against LLVM 19.1.0

### ISSUE THREAD

**Issue by wenju-he** [KhronosGroup/SPIRV-LLVM-Translator#2720]
[LLVM 19.1.0](https://github.com/llvm/llvm-project/releases/tag/llvmorg-19.1.0) is now released.

**Comment by svenvh** [comment]
I've created release https://github.com/KhronosGroup/SPIRV-LLVM-Translator/releases/tag/v19.1.0

**Comment by wenju-he** [comment]
thank you @svenvh
