### ISSUE TITLE
[llvm_release_190] Option 'spirv-ext' registered more than once!

### ISSUE THREAD

**Issue by linehill** [KhronosGroup/SPIRV-LLVM-Translator#2737]
This happen when the experimental SPIR-V backend is enabled in LLVM-19 (`-DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD="SPIRV"`).

```
$ ./llvm-spirv --version
: CommandLine Error: Option 'spirv-ext' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
Aborted (core dumped)
```

**Comment by svenvh** [comment]
Thanks for the report.  I believe we will need to backport the workaround we have on `main` already (that is, first check if the option is already registered and if so, rename it; then register llvm-spirv's own `spirv-ext` option.

**Comment by svenvh** [comment]
The fix should look something like https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2738

**Comment by svenvh** [comment]
I wondered if this needs backporting to older release branches, but I believe it doesn't.  The llvm-project commit that introduced the "duplicate" `-spirv-ext` option (`d06ba376833553f38b5cbc606e479ed7936e5f5b`) is only llvm's `release/19.x` branch.
