### ISSUE TITLE
OpenCL file compiled by Khronos OpenCL Clang compiler+SPIRV-LLVM using cl_intel_subgroups+cl_intel_subgroups_short omits needed OpExtension "SPV_INTEL_subgroups" and also Vector16 capability in generated SPIR-V

### ISSUE THREAD

**Issue by AlexeySotkin** [KhronosGroup/SPIRV-LLVM-Translator#28]
To continue tracking issue https://github.com/KhronosGroup/SPIRV-LLVM/issues/228 from the old repository.

**Comment by imashkov** [comment]
Vector16 is not a problem now: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/master/test/transcoding/vec8.ll
But we need to fix problem with "SPV_INTEL_subgroups", i will do it.

**Comment by AlexeySachkov** [comment]
Should be fixed by #312
