### ISSUE TITLE
LLVM-SPIRV crashes on struct with vector-content

### ISSUE THREAD

**Issue by AlexeySotkin** [KhronosGroup/SPIRV-LLVM-Translator#29]
To continue tracking issue https://github.com/KhronosGroup/SPIRV-LLVM/issues/206 from the old repository.

**Comment by imashkov** [comment]
I can not reproduce it anymore. @AlexeySotkin, please, close.

**Comment by AlexeySotkin** [comment]
Thanks, @imashkov
