### ISSUE TITLE
enqueue_kernel builtins translation - SPIRV to LLVM fails

### ISSUE THREAD

**Issue by hewj03** [KhronosGroup/SPIRV-LLVM-Translator#331]
OpenCL CTS Device_execution21_offline/test_enqueue_block failure is caused by the following commit:
commit d68d83bed67861af79999dbf1edcbd480778ec51
Author: Andrzej Ratajewski <andrzej.ratajewski@intel.com>
Date:   Mon Aug 19 12:48:43 2019 +0200
    Fix enqueue_kernel builtins translation - SPIRV to LLVM

The following kernel is translated to __enqueue_kernel_basic instead of __enqueue_kernel_basic_events:
    int enq_res = enqueue_kernel(def_q, CLK_ENQUEUE_FLAGS_NO_WAIT, ndrange, 0, NULL, &block_evt1, kernelBlock);

**Comment by AlexeySachkov** [comment]
@aratajew: FYI
