### ISSUE TITLE
Please make a release against llvm-9

### ISSUE THREAD

**Issue by dvrogozh** [KhronosGroup/SPIRV-LLVM-Translator#334]
It seems llvm-9 is finally out. Can you, please, tag a release on your side since this is required for packaging in the distros. For example, Ubuntu 19.10 might wish to go with llvm-9.

**Comment by AlexeySachkov** [comment]
I guess we need to finish with #332 and #316 prior making a final release

**Comment by dvrogozh** [comment]
I can advice here. I guess there are 2 options to consider:
1. Make release with the current code (+ those PR you can merge in right now) and provide release update later
2. Wait for everything you have on a plate merged in.

That's definitely teams choice.

**Comment by tjaalton** [comment]
Hi, thanks for considering an update. Ubuntu 19.10 will release on Oct 17th and will freeze roughly a week before, so a release within the next week or so would be nice. The default LLVM version is already 9 and Mesa (for instance) will switch to it this week.

**Comment by svenvh** [comment]
#332 and #316 have been merged to the llvm_release_90 branch now.

@AlexeySotkin, I suppose the branch is in a good shape to make a release now?

**Comment by AlexeySotkin** [comment]
Sure. I was going to make it today.

**Comment by AlexeySotkin** [comment]
I have created a draft for LLVM-9-based release.
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/releases/tag/untagged-7cc7eba135c1018c01be
 @svenvh @AnastasiaStulova @AlexeySachkov @neildhickey please take a look. Please let me know if you have any comments.

**Comment by pierremoreau** [comment]
@AlexeySotkin Would it be possible to update `LLVM_SPIRV_VERSION` in CMakeLists.txt to 9.0.0 (or whichever version of LLVM it is based on)?

I was planning on sending merge requests for it after realising #131 hadn’t been addressed yet, but you’ll probably get around to making the release before I have time to send them (I won’t be able to make them before several hours).
This is now an issue in Mesa, as we are currently relying on the API from after https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/5f710f2934816f11cfacdf7bd611b35470d96dbd but all the released version before and after that commit, have the same 0.2.1 version in CMake, so we can’t ensure getting a correct version in the build system.

**Comment by AlexeySotkin** [comment]
I think it is possible. @tjaalton, @dvrogozh  any concerns regarding changing the version here https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/1b09eaf860e0d41dfe284bdaec7aaddbad17147c/LLVMSPIRVLib.pc.in#L8

**Comment by tjaalton** [comment]
seems fine, and uploaded to debian now

**Comment by AlexeySotkin** [comment]
The release is here https://github.com/KhronosGroup/SPIRV-LLVM-Translator/releases/tag/v9.0.0-1

**Comment by dvrogozh** [comment]
Thank you!
