### ISSUE TITLE
Website needs update

### ISSUE THREAD

**Issue by mfwitten** [KhronosGroup/SPIRV-LLVM-Translator#337]
Please update this website:

* <https://www.khronos.org/opencl/>

Currently, it leads newcomers down an old path to a dead end; it needs to point them instead to the following facts (as far as I can tell):

* The [official `clang` project](https://clang.llvm.org) is now the home of OpenCL front-end development; it can target particular devices or the LLVM bitcode.

* Khronos Group's role is developing tools to translate LLVM bitcode to SPIR-V bitcode (and vice versa); this work is held in the [SPIRV-LLVM-Translator&nbsp;repo](https://github.com/KhronosGroup/SPIRV-LLVM-Translator).

* Intel is developing "[Common&nbsp;clang](https://github.com/intel/opencl-clang/)" (seriously?) that uses both `clang` and `SPIRV-LLVM-Translator` projects to provide an OpenCL-specific command-line interface to `clang`, and which thereby produces SPIR-V output from OpenCL input (without having to fiddle with any other intermediate representation).

**Comment by AlexeySachkov** [comment]
Hi @mfwitten, I think this issue should be transferred into [KhronosGroup/OpenCL-Registry](https://github.com/KhronosGroup/OpenCL-Registry) repo that actually contains the content of mentioned website and since it is open-source too, you could suggest your changes via pull request there

**Comment by mfwitten** [comment]
Fix the website.

**Comment by bader** [comment]
+@pierremoreau suggestions on LLVM-SPIRV repository updates in addition to the Khronos web-page.
https://github.com/KhronosGroup/SPIRV-LLVM/pull/238#issuecomment-534630735

**Comment by AlexeySachkov** [comment]
We have updated the link to the translator in the [resources page](https://www.khronos.org/opencl/resources) and archived outdated SPIRV-LLVM repo. I'm going to close this now as fixed.

If there are other requests to improve the site, they should be posted in the [corresponding repo](https://github.com/KhronosGroup/Khronosdotorg/)
