### ISSUE TITLE
OpIEqual can't be used for pointers

### ISSUE THREAD

**Issue by karolherbst** [KhronosGroup/SPIRV-LLVM-Translator#35]
if a pointer is compared against NULL, an OpIEqual instruction is generated with the sources being pointers.

The spec states for OpIEqual: "The type of Operand 1 and Operand 2 must be a scalar or vector of integer type. They must have the same component width, and they must have the same number of components as Result Type."

So I think OpConvertPtrToU have to be inserted before using OpIEqual.

example code:

```OpenCL
kernel void
test(ulong global* in)
{
        if (!in)
                return;
        *in += 4;
}
```

```SPIR-V
; SPIR-V
; Version: 1.0
; Generator: Khronos LLVM/SPIR-V Translator; 14
; Bound: 19
; Schema: 0
               OpCapability Addresses
               OpCapability Kernel
               OpCapability Int64
          %1 = OpExtInstImport "OpenCL.std"
               OpMemoryModel Physical64 OpenCL
               OpEntryPoint Kernel %6 "test"
               OpSource OpenCL_C 102000
      %ulong = OpTypeInt 64 0
    %ulong_4 = OpConstant %ulong 4
       %void = OpTypeVoid
%_ptr_CrossWorkgroup_ulong = OpTypePointer CrossWorkgroup %ulong
          %5 = OpTypeFunction %void %_ptr_CrossWorkgroup_ulong
       %bool = OpTypeBool
         %11 = OpConstantNull %_ptr_CrossWorkgroup_ulong
       %true = OpConstantTrue %bool
          %6 = OpFunction %void None %5
          %7 = OpFunctionParameter %_ptr_CrossWorkgroup_ulong
          %8 = OpLabel
         %13 = OpIEqual %bool %7 %11
         %15 = OpLogicalNotEqual %bool %13 %true
               OpSelectionMerge %10 None
               OpBranchConditional %15 %9 %10
          %9 = OpLabel
         %16 = OpLoad %ulong %7 Aligned 8
         %18 = OpIAdd %ulong %16 %ulong_4
               OpStore %7 %18 Aligned 8
               OpBranch %10
         %10 = OpLabel
               OpReturn
               OpFunctionEnd
```

spirv-val output:
```
error: 19: Expected operands to be scalar or vector int: IEqual
```

**Comment by karolherbst** [comment]
SPIRV 1.4 added OpPtrEqual and OpPtrNotEqual in order to let us compare pointers, but maybe it would be too harsh to require 1.4?

Otherwise in order to fix that we would have to cast pointers to unsigned integers and compare these.

**Comment by kpet** [comment]
+1, I've hit a similar problem. Here's a module to reproduce:

```
source_filename = "repro.cl"
target datalayout = "e-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024"
target triple = "spir64-unknown-unknown"

define spir_kernel void @test(i8 addrspace(1)* %aptr, i8 addrspace(1)* %bptr) local_unnamed_addr #0 !kernel_arg_addr_space !1 !kernel_arg_access_qual !2 !kernel_arg_type !3 !kernel_arg_base_type !3 !kernel_arg_type_qual !4 {
entry:
  %cmp213 = icmp ugt i8 addrspace(1)* %aptr, %bptr
  ret void
}

attributes #0 = { "use-soft-float"="false" }
attributes #1 = { nounwind readnone speculatable }

!llvm.ident = !{!0}

!0 = !{!"clang version 9.0.0 "}
!1 = !{i32 1, i32 1}
!2 = !{!"none", !"none"}
!3 = !{!"uchar*", !"uchar*"}
!4 = !{!"", !""}
```

The SPIR-V produced is

```
; SPIR-V
; Version: 1.0
; Generator: Khronos LLVM/SPIR-V Translator; 14
; Bound: 13
; Schema: 0
               OpCapability Addresses
               OpCapability Kernel
               OpCapability Int8
          %1 = OpExtInstImport "OpenCL.std"
               OpMemoryModel Physical64 OpenCL
               OpEntryPoint Kernel %6 "test"
         %12 = OpString "kernel_arg_type.test.uchar*,uchar*,"
               OpSource Unknown 0
               OpName %aptr "aptr"
               OpName %bptr "bptr"
               OpName %entry "entry"
               OpName %cmp213 "cmp213"
      %uchar = OpTypeInt 8 0
       %void = OpTypeVoid
%_ptr_CrossWorkgroup_uchar = OpTypePointer CrossWorkgroup %uchar
          %5 = OpTypeFunction %void %_ptr_CrossWorkgroup_uchar %_ptr_CrossWorkgroup_uchar
       %bool = OpTypeBool
          %6 = OpFunction %void None %5
       %aptr = OpFunctionParameter %_ptr_CrossWorkgroup_uchar
       %bptr = OpFunctionParameter %_ptr_CrossWorkgroup_uchar
      %entry = OpLabel
     %cmp213 = OpUGreaterThan %bool %aptr %bptr
               OpReturn
               OpFunctionEnd
```

which fails validation

```
error: line 22: Expected operands to be scalar or vector int: UGreaterThan
  %cmp213 = OpUGreaterThan %bool %aptr %bptr
```

**Comment by kpet** [comment]
@karolherbst We do need a solution pre-1.4. It seems that converting to integers is the only way. FWIW, the LLVM language reference manual states
```
If the operands are pointer typed, the pointer values are compared as if they were integers.
```

**Comment by karolherbst** [comment]
yeah, I think converting to integers pre 1.4 is valid, I would just support both ways. And I think there is already the assumption that the consumer always has to be able to support the most recent spirv version...

might be worth to kind of being able to tell what's the highest version the consumer supports and then disabling certain features or something.

**Comment by AlexeySachkov** [comment]
> And I think there is already the assumption that the consumer always has to be able to support the most recent spirv version...

Really? For example, [intel/compute-runtime](https://github.com/intel/compute-runtime/issues/110#issuecomment-487019459) supports only SPIR-V 1.2

> might be worth to kind of being able to tell what's the highest version the consumer supports and then disabling certain features or something.

I think we definitely need this, see #110 for appropriate discussion.

**Comment by karolherbst** [comment]
> > And I think there is already the assumption that the consumer always has to be able to support the most recent spirv version...
> 
> Really? For example, [intel/compute-runtime](https://github.com/intel/compute-runtime/issues/110#issuecomment-487019459) supports only SPIR-V 1.2
> 

oh, could be that I am wrong. I think some future spir-v feature was enabled without the extension... would have to search for it again.
