### ISSUE TITLE
Translation result

### ISSUE THREAD

**Issue by Keryen** [KhronosGroup/SPIRV-LLVM-Translator#372]
I have one doubt that i tried to prove by myself, but i cannot resolve it.

If I have a bytecode file, I translate it into SPIR-V format, and I transform it again to a bytecode file, the result is exactly the same as the initial bytecode?

**Comment by Naghasan** [comment]
It should be semantically be the same but a diff will show differences. That's due to some necessary lowering being done.

**Comment by AlexeySachkov** [comment]
Another one thing is that SPIR-V cannot represent all LLVM IR things: for example, most of function attributes and metadata will be missed

**Comment by MrSidims** [comment]
Closing as Stale. In general the translator tries to preserve as much of original LLVM IR as possible in a round-trip, but as it's mentioned sometimes we have to drop something not representable in SPIR-V and emulate some intrinsic functions.
