### ISSUE TITLE
__builtin_popcount yields Unexpected llvm intrinsic

### ISSUE THREAD

**Issue by davidrohr** [KhronosGroup/SPIRV-LLVM-Translator#441]
Compiling OpenCL C++ code that uses __builtin_popcount with latest clang 659500c0c9657fc6e8d2d184b507f4e4da99297e and the latest translater 39edc1dcd71bb08304ab65b1f3a8e5fb90ca40ac yields the following error:

InvalidFunctionCall: Unexpected llvm intrinsic: llvm.ctpop.i32 [Src: /home/qon/clang-build/SPIRV-LLVM-Translator/lib/SPIRV/SPIRVWriter.cpp:1764  ]
Stack dump:
0.      Program arguments: /home/qon/clang-build/SPIRV-LLVM-Translator/build/tools/llvm-spirv/llvm-spirv test.bc 
1.      Running pass 'LLVMToSPIRV' on module 'test.bc'.
 #0 0x00005586f2485599 llvm::sys::PrintStackTrace(llvm::raw_ostream&) /home/qon/clang-build/llvm-project/llvm/lib/Support/Unix/Signals.inc:564:22
 #1 0x00005586f248562c PrintStackTraceSignalHandler(void*) /home/qon/clang-build/llvm-project/llvm/lib/Support/Unix/Signals.inc:625:1
 #2 0x00005586f24833d5 llvm::sys::RunSignalHandlers() /home/qon/clang-build/llvm-project/llvm/lib/Support/Signals.cpp:68:20
 #3 0x00005586f2484f19 SignalHandler(int) /home/qon/clang-build/llvm-project/llvm/lib/Support/Unix/Signals.inc:406:1
 #4 0x00007f6f99dad370 __restore_rt (/lib64/libpthread.so.0+0x15370)
 #5 0x00007f6f997b61e1 raise (/lib64/libc.so.6+0x3a1e1)
 #6 0x00007f6f9979e55b abort (/lib64/libc.so.6+0x2255b)
 #7 0x00005586f1b044be SPIRV::SPIRVErrorLog::checkError(bool, SPIRV::SPIRVErrorCode, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, char const*, unsigned int) (/home/qon/clang-build/SPIRV-LLVM-Translator/build/tools/llvm-spirv/llvm-spirv+0xa014be)
 #8 0x00005586f1bd7772 SPIRV::LLVMToSPIRV::transIntrinsicInst(llvm::IntrinsicInst*, SPIRV::SPIRVBasicBlock*) (/home/qon/clang-build/SPIRV-LLVM-Translator/build/tools/llvm-spirv/llvm-spirv+0xad4772)
 #9 0x00005586f1bd4420 SPIRV::LLVMToSPIRV::transValueWithoutDecoration(llvm::Value*, SPIRV::SPIRVBasicBlock*, bool) (/home/qon/clang-build/SPIRV-LLVM-Translator/build/tools/llvm-spirv/llvm-spirv+0xad1420)
#10 0x00005586f1bd092d SPIRV::LLVMToSPIRV::transValue(llvm::Value*, SPIRV::SPIRVBasicBlock*, bool) (/home/qon/clang-build/SPIRV-LLVM-Translator/build/tools/llvm-spirv/llvm-spirv+0xacd92d)
#11 0x00005586f1bd9126 SPIRV::LLVMToSPIRV::transFunction(llvm::Function*) (/home/qon/clang-build/SPIRV-LLVM-Translator/build/tools/llvm-spirv/llvm-spirv+0xad6126)
#12 0x00005586f1bd97a1 SPIRV::LLVMToSPIRV::translate() (/home/qon/clang-build/SPIRV-LLVM-Translator/build/tools/llvm-spirv/llvm-spirv+0xad67a1)
#13 0x00005586f1bcc31a SPIRV::LLVMToSPIRV::runOnModule(llvm::Module&) (/home/qon/clang-build/SPIRV-LLVM-Translator/build/tools/llvm-spirv/llvm-spirv+0xac931a)
#14 0x00005586f22b5353 (anonymous namespace)::MPPassManager::runOnModule(llvm::Module&) /home/qon/clang-build/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1583:20
#15 0x00005586f22b5b70 llvm::legacy::PassManagerImpl::run(llvm::Module&) /home/qon/clang-build/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1695:13
#16 0x00005586f22b5d6d llvm::legacy::PassManager::run(llvm::Module&) /home/qon/clang-build/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1727:1
#17 0x00005586f1bdc6d8 llvm::writeSpirv(llvm::Module*, SPIRV::TranslatorOpts const&, std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (/home/qon/clang-build/SPIRV-LLVM-Translator/build/tools/llvm-spirv/llvm-spirv+0xad96d8)
#18 0x00005586f1ad3805 convertLLVMToSPIRV(SPIRV::TranslatorOpts const&) (/home/qon/clang-build/SPIRV-LLVM-Translator/build/tools/llvm-spirv/llvm-spirv+0x9d0805)
#19 0x00005586f1ad5e4b main (/home/qon/clang-build/SPIRV-LLVM-Translator/build/tools/llvm-spirv/llvm-spirv+0x9d2e4b)
#20 0x00007f6f9979fe7b __libc_start_main (/lib64/libc.so.6+0x23e7b)
#21 0x00005586f1ad341a _start (/home/qon/clang-build/SPIRV-LLVM-Translator/build/tools/llvm-spirv/llvm-spirv+0x9d041a)

**Comment by AlexeySachkov** [comment]
Ops,

**Comment by AlexeySachkov** [comment]
Should be fixed by KhronosGroup/SPIRV-LLVM-Translator#775
