### ISSUE TITLE
Internal defines of OpForward and LinkageTypeInternal

### ISSUE THREAD

**Issue by MrSidims** [KhronosGroup/SPIRV-LLVM-Translator#460]
Hi,

I'm working on updating spirv.core.grammar.json file in https://github.com/KhronosGroup/SPIRV-Headers repository to propagate translator-specific changes into generated spirv.hpp header, so later it can be re-used in this repository, as it was asked, for example, here: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/397#pullrequestreview-334580214 .

After update of the json grammar file and generation of fresh-new spirv.hpp header I found out, that OpForward and LinkageTypeInternal aren't presenting in it, because there are internal undocumented defines.

So my question is: do we plan to document and upstream them?

As far as I understand, we never place OpForward instruction and the appropriate decoration for LinkageTypeInternal in SPIR-V module, so it might be possible to get rid of them in the translator's sources somehow saving information they cover for the translator.

**Comment by MrSidims** [comment]
Tagging @AlexeySotkin @svenvh @bashbaug @AlexeySachkov .

**Comment by bashbaug** [comment]
> I found out, that OpForward and LinkageTypeInternal aren't presenting in it, because there are internal undocumented defines.

I've noticed this also.  Even if they are needed, could they be moved to a separate file?  Ideally we should be able to use the off-the-shelf spirv.hpp, without needing any manual changes.

**Comment by svenvh** [comment]
@MrSidims great to see progress on this!

I agree with @bashbaug that ultimately we should be able to use a clean `spirv.hpp`.  I believe `OpForward` and `LinkageTypeInternal` are internal to the translator to assist the translation process, so we probably don't want to upstream them.  Moving them to a separate file seems like a good solution.

Perhaps we might eventually be able to get rid of them by refactoring the translator.

**Comment by MrSidims** [comment]
Fixed with https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/573
