### ISSUE TITLE
Wrong target branch in the check_code_format.sh.

### ISSUE THREAD

**Issue by AlexeySotkin** [KhronosGroup/SPIRV-LLVM-Translator#496]
There is a strange problem with check_code_format.sh. As I see from the source, it gets diff between master and current commit.
`FORMAT_DIFF=$(git diff -U0 master -- ${FILES_TO_CHECK} | ./utils/clang-format-diff.py -p1 -style=file)`
This is not correct for release branches -- diff should be taken between release branch and commit to this branch. In this PR this led to the problem, that script found problem in the code that was not modified by this particular PR. This part of code was modified in my previous PR to master branch, and with this PR script thinks that the code was reformatted back and raises an error.
PR 490 is merged, and I will just rebase this change on top of 90 branch. The error should disappear. However, there still will be an error in check_code_format.sh.

_Originally posted by @aus-intel in https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/491#issuecomment-614583164_

**Comment by AlexeySachkov** [comment]
I removed that script in #770 during switch to GitHub Actions, so this is not actual anymore, closing
