### ISSUE TITLE
LLVM version support policy

### ISSUE THREAD

**Issue by pierremoreau** [KhronosGroup/SPIRV-LLVM-Translator#5]
The code seems to currently only build against LLVM 7.0, which hasn’t been released yet. I do not know whether a policy has already been decided on which versions of LLVM to support,but I think we should at the very least support the latest release version. And I would definitely agree with tracking LLVM HEAD as closely as possible.

**Comment by neildhickey** [comment]
We now have a branch of the project working against version 7.0 of the llvm release as well as master. Our plan going forward is to track all LLVM releases from this point on.
