### ISSUE TITLE
Incorrect code in SPIRVLowerMemmove.cpp

### ISSUE THREAD

**Issue by AlexeySachkov** [KhronosGroup/SPIRV-LLVM-Translator#500]
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/b656125fb2ad0295f910630f1b3efcdab4f88dfe/lib/SPIRV/SPIRVLowerMemmove.cpp#L88-L103

As you can see, there is assumption that `SrcTy` might be an `ArrayType` at lines 88-90. However, at line 103 we call `getElementPointerType` which assumes that `SrcTy` is a `PointerType`

I guess that code path with `ArrayType` is not tested properly

**Comment by MrSidims** [comment]
It seems like not an issue anymore, at least the code was significantly changed. Closing, feel free to re-open if disagree.
