### ISSUE TITLE
To consider enabling tests which check OpenCL C to SPIR-V translation

### ISSUE THREAD

**Issue by AlexeySotkin** [KhronosGroup/SPIRV-LLVM-Translator#54]
This kind of end-to-end testing should help us to keep compatibility with Clang on LLVM IR level.

**Comment by AlexeySachkov** [comment]
Here is an example of end-to-end test: https://github.com/AlexeySachkov/SPIRV-LLVM-Translator/pull/1

Looks like everything is working out of the box - we need just to add some tests

**Comment by AnastasiaStulova** [comment]
May be we can just setup whatever is easier to start from and then incrementally improve this with time.

**Comment by svenvh** [comment]
Implemented by https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/169
