### ISSUE TITLE
Incorrect Handling of Kernel Function Calling Another Kernel Function

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/SPIRV-LLVM-Translator#598]
See:

https://github.com/KhronosGroup/SPIRV-Registry/issues/74

In summary, the SPIRV-LLVM-Translator is currently generating invalid SPIR-V when one kernel function calls another kernel function, in some cases.  For example:

```c
kernel void func( global uint* dst ) {
    dst[0] = 42;
}

kernel void kern( global uint* dst ) {
    func(dst);
}
```

Compiling with:

```sh
clang -c -cl-std=CL1.2 -target spir64 -emit-llvm -Xclang -finclude-default-header -g0 -O0 call_kernel.cl
llvm-spirv call_kernel.bc -o call_kernel.spv
```

Generates:

```
; SPIR-V
; Version: 1.0
; Generator: Khronos LLVM/SPIR-V Translator; 14
; Bound: 25
; Schema: 0
               OpCapability Addresses
               OpCapability Kernel
               OpCapability Int64
          %1 = OpExtInstImport "OpenCL.std"
               OpMemoryModel Physical64 OpenCL
               OpEntryPoint Kernel %6 "func"
               OpEntryPoint Kernel %16 "kern"
         %22 = OpString "kernel_arg_type.func.uint*,"
         %23 = OpString "kernel_arg_type.kern.uint*,"
               OpSource OpenCL_C 102000
               OpDecorate %24 Alignment 8
         %24 = OpDecorationGroup
               OpGroupDecorate %24 %10 %19
       %uint = OpTypeInt 32 0
      %ulong = OpTypeInt 64 0
    %ulong_0 = OpConstant %ulong 0
    %uint_42 = OpConstant %uint 42
       %void = OpTypeVoid
%_ptr_CrossWorkgroup_uint = OpTypePointer CrossWorkgroup %uint
          %5 = OpTypeFunction %void %_ptr_CrossWorkgroup_uint
%_ptr_Function__ptr_CrossWorkgroup_uint = OpTypePointer Function %_ptr_CrossWorkgroup_uint
          %6 = OpFunction %void DontInline %5
          %7 = OpFunctionParameter %_ptr_CrossWorkgroup_uint
          %8 = OpLabel
         %10 = OpVariable %_ptr_Function__ptr_CrossWorkgroup_uint Function
               OpStore %10 %7 Aligned 8
         %11 = OpLoad %_ptr_CrossWorkgroup_uint %10 Aligned 8
         %14 = OpInBoundsPtrAccessChain %_ptr_CrossWorkgroup_uint %11 %ulong_0
               OpStore %14 %uint_42 Aligned 4
               OpReturn
               OpFunctionEnd
         %16 = OpFunction %void DontInline %5
         %17 = OpFunctionParameter %_ptr_CrossWorkgroup_uint
         %18 = OpLabel
         %19 = OpVariable %_ptr_Function__ptr_CrossWorkgroup_uint Function
               OpStore %19 %17 Aligned 8
         %20 = OpLoad %_ptr_CrossWorkgroup_uint %19 Aligned 8
         %21 = OpFunctionCall %void %6 %20
               OpReturn
               OpFunctionEnd
```

This is properly identified as an error by `spirv-val`:

```
error: line 22: A function (6) may not be targeted by both an OpEntryPoint instruction and an OpFunctionCall instruction.
  %6 = OpFunction %void DontInline %5
```

Note that running `clang` with higher optimization levels will generate valid SPIR-V for this case, since the contents of the other kernel function is inlined into this kernel function, but this is not a good general-purpose solution.

One possible solution is to perform the transform described here: https://github.com/KhronosGroup/SPIRV-Registry/issues/74#issuecomment-645134572

**Comment by jenatali** [comment]
This is related to #587, except that #587 requires a declaration of a kernel and a call in one module, and an implementation of that kernel in another module.

Assuming that the solution is performing the transform described by https://github.com/KhronosGroup/SPIRV-Registry/issues/74#issuecomment-645134572, any extern forward-declarations of a kernel should actually be forward-declarations of the kernel *implementation*, rather than the entry-point. That will allow linking to work correctly.

**Comment by SamB** [comment]
Did https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1149 fix this case too?

**Comment by jenatali** [comment]
Sorry for the long delay, I've finally gotten around to updating to a newer version of LLVM and the translator. I can confirm that with this change in place I'm no longer seeing failures.
