### ISSUE TITLE
Intergration w LLVM

### ISSUE THREAD

**Issue by AnastasiaStulova** [KhronosGroup/SPIRV-LLVM-Translator#68]
How to integrate this tool with the rest of LLVM to provide seamless flow for the developers.

TODO: A number of upstream threads to be summarized here.

**Comment by MrSidims** [comment]
Probably can be closed. Integration with LLVM is happening by adding SPIR-V backend (and possibly later SPIR-V consumer). Closing. FYI @svenvh @VyacheslavLevytskyy
