### ISSUE TITLE
Translation of barrier bulitins from OpenCL to SPIR-V

### ISSUE THREAD

**Issue by AlexeySotkin** [KhronosGroup/SPIRV-LLVM-Translator#70]
OpenCL barrier and work_group_barrier bulitins have argument of cl_mem_fence_flags type which specifies local or global address space. While in SPIR-V OpControlBarrier has ‘Memory Semantics’ operand which specifies both memory-order constraints, and on what storage classes those constraints apply to. OpenCL address space maps fine to SPIRV storage class, but what about memory-order? According to the description here https://www.khronos.org/registry/OpenCL/sdk/2.1/docs/man/xhtml/work_group_barrier.html it seems like OpenCL barrier _implies_ acquire-release memory-order semantics, doesn’t it?
If yes, should we always set AcquireRelease bit in the ‘Memory Semantics’ operand translating OpenCL [working_group_]barrier to OpControlBarrier in SPIR-V ?

**Comment by AlexeySotkin** [comment]
https://www.khronos.org/registry/OpenCL/sdk/2.0/docs/man/xhtml/work_group_barrier.html  

> The flags argument specifies the memory address spaces and can be set to 0 or a combination of the following values ORed together

**Comment by neildhickey** [comment]
Ah great thanks, yes I'd missed that :)

One more thing, are we sure acquire_release, rather than seq_cst is the correct default here? sequential consistency would be the most conservative of the options available.

**Comment by AlexeySotkin** [comment]
I have updated the PR with seq_cst memory semantics used by default and relaxed semantics if mem fence flags are set to 0.
