### ISSUE TITLE
Add Windows to the CI

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/SPIRV-LLVM-Translator#726]
The build of the translator regularly breaks on Windows due to the lack of testing. This makes it hard for projects embedding the translator to support Windows.

**Comment by AlexeySachkov** [comment]
Hi @kpet,

> The build of the translator regularly breaks on Windows due to the lack of testing

We are using the translator at intel/llvm and we have Windows build there in pre-commits: from my personal experience, it is quite stable and honestly, I don't remember any PR about fixing build specifically on Windows. Could you please share a bit more info probably? Like particular commits that broke something?

I'm not against adding Win build to the CI, just my experience is a bit different: sometimes LIT tests fail on Windows only, but not build. For example: intel/llvm#2433, #230, #183 

Regarding the request itself: I think we should start with in-tree builds as it seems to be the simplest step form my point of view: I honestly have no idea how to obtain pre-built LLVM & clang on Windows

**Comment by kpet** [comment]
I've seen this a couple of times and I ended up [disabling SPIR-V consumption on Windows](https://github.com/kpet/clvk/commit/1c3c541774cf35fde0ce238b4bc41dbf74fa8f86) in clvk so the translator commit used there (207924d) definitely didn't build in my test environment. The complete lack of upstream Windows testing made me think that it was not something I could commit to chase but maybe I could give this another go if you're confident Intel has good coverage internally. It would still be nice to get some upstream testing though, if anything to make what is being tested systematically visible.

**Comment by kpet** [comment]
I've now re-enabled SPIR-V consumption on Windows in clvk. I'll comment here if/when I'm facing issues.

**Comment by AlexeySachkov** [comment]
Hi @kpet,

We are experimenting with GitHub Actions (#818) and I've just enabled build of the translator on Windows: I can't say for sure whether we will stick with GitHub Actions or return back to Travis CI so I won't close this issue yet. Also, I haven't enabling testing on Windows

**Comment by MrSidims** [comment]
Closing as we stick with github actions. Unfortunately not on every branch yet, but hope to resolve soon.
