### ISSUE TITLE
intree documentation does not build

### ISSUE THREAD

**Issue by DieracDelta** [KhronosGroup/SPIRV-LLVM-Translator#777]
I'm on linux (and have reproduced the problem on windows). Following the in-tree build instructions at verbatim in the README gives the following error:

```
CMake Error at cmake/modules/AddLLVM.cmake:1730 (add_dependencies):
  The dependency target "clang" of target "check-all" does not exist.
Call Stack (most recent call first):
  CMakeLists.txt:1071 (add_lit_target)


CMake Error at cmake/modules/AddLLVM.cmake:1730 (add_dependencies):
  The dependency target "clang" of target "check-llvm-spirv" does not exist.
Call Stack (most recent call first):
  cmake/modules/AddLLVM.cmake:1751 (add_lit_target)
  projects/SPIRV-LLVM-Translator/test/CMakeLists.txt:69 (add_lit_testsuite)
```

This goes away only when I (1) clone into the `llvm-project/tools` directory and (2) run cmake with the `-DLLVM_INCLUDE_TESTS=OFF` flag. If yall can confirm this is a problem, I can update the documentation and put together a PR with the commands that allowed me to build.

**Comment by AlexeySachkov** [comment]
Hi @DieracDelta, this is indeed a bug in our README caused by the fact that we require `clang` to be present for our tests.

I've submitted #778 to clarify that, could you please take a look at it and provide your feedback?

**Comment by DieracDelta** [comment]
Thanks for correcting this!
