### ISSUE TITLE
LLVM 11 based release?

### ISSUE THREAD

**Issue by ArchangeGabriel** [KhronosGroup/SPIRV-LLVM-Translator#786]
Hi there,

Arch Linux packager here. ;) We just added LLVM 11 to our tree and are starting rebuilding all stacks against it. Should we expect an LLVM 11 based release here soon or not? :) No pressure at all, this is just for us to decide whether we want to wait for an eventual new release or whether we will move this stack to a separate LLVM 10 build.

Regards,
Bruno/Archange

CC @dbermond.

**Comment by svenvh** [comment]
We already have a branch that is based on LLVM 11 (`llvm_release_110`), so expect an LLVM 11 based release at some point.  @AlexeySotkin or @AlexeySachkov can probably give an estimate of when it will be available.

**Comment by AlexeySotkin** [comment]
Hi @ArchangeGabriel. We are currently working on the LLVM 11 based release, so I'd expect the release soon.

**Comment by AlexeySachkov** [comment]
@ArchangeGabriel, here you go: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/releases/tag/v11.0.0

**Comment by ArchangeGabriel** [comment]
Awesome, thank you! Succesfully built on Arch. :)
