### ISSUE TITLE
Discussion about clang-tidy CI check

### ISSUE THREAD

**Issue by AlexeySachkov** [KhronosGroup/SPIRV-LLVM-Translator#801]
Hi,

This would be a follow-up from #770: so far we had only two failures of [Check code-style workflow](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/actions?query=workflow%3A%22Check+code+style%22): [first](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/runs/1281193465?check_suite_focus=true), [second](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/runs/1275816326?check_suite_focus=true).

In both cases, `clang-tidy` failed, but logs don't contain any errors, but only warnings. The workflow failed because it just checks if log is non-empty.

Therefore, I have a few questions:

- do we care about warnings from `clang-tidy`? If yes, then we can leave workflow file as-is or update it to pass something like `-Werror` to `clang-tidy` (if such exists) and grep for `error:`. Otherwise, we need to update the workflow to grep for `error:`
- do we need to re-evaluate list of checks enabled? Probably we do not care about warnings, but would like to turn `readability-identifier-naming` into an error, i.e. make it a mandatory check?

It would be good to have a way to highlight somehow that check was completed successfully, but there are some warnings. However, I'm not sure that this is possible (or easily possible) with current GitHub Actions functionality.

Tagging @svenvh  and @AlexeySotkin for feedback.

**Comment by svenvh** [comment]
> do we care about warnings from clang-tidy?

I think so; this is how the check worked with Travis too, right?  I think it helps to keep the code follow the coding style.  If we see warnings that we do not care about, then we should probably try to suppress them, but currently I am not aware of any that we want to suppress.

**Comment by svenvh** [comment]
> I've decided to turn warnings from the checks we have enabled to errors to better clarify that these are must-fix things.

That makes sense.

> Also, clang-tidy messages will now be published directly on "Files changed" page

That looks very handy indeed!
