### ISSUE TITLE
Unexpected llvm intrinsic during llvm-spirv translation

### ISSUE THREAD

**Issue by davidrohr** [KhronosGroup/SPIRV-LLVM-Translator#890]
The attached test case (I am adding both the opencl source file and the llvm bc file) fails to convert to llvm-spirv with the error
```
InvalidFunctionCall: Unexpected llvm intrinsic:
 llvm.experimental.noalias.scope.decl [Src: /home/qon/tmp9/llvm-project/llvm/projects/SPIRV-LLVM-Translator/lib/SPIRV/SPIRVWriter.cpp:2752  ]
```
I am using llvm commit dfb558b82d3f2ca228799b03d2be00b163d04ea5 + the 2 fixes referenced in https://bugs.llvm.org/show_bug.cgi?id=48896 and llvm-spirv commit 5b641633b3bcc3251a52260eee11db13a79d7258.

[testcase.tar.gz](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/files/5888925/testcase.tar.gz)

Commands to reproduce:
cl --> bc:
```
clang++ -cl-std=clc++ -x cl -emit-llvm --target=spir64-unknown-unknown -O3 -cl-denorms-are-zero -cl-mad-enable -cl-no-signed-zeros -ferror-limit=1000 -Xclang -finclude-default-header -Dcl_clang_storage_class_specifiers -c test.cl -o test.bc
```
bc --> spirv
```
llvm-spirv test.bc
```

Ping @AnastasiaStulova : The llvm compilation works now, but unfortunately the spirv conversion step fails.

**Comment by AnastasiaStulova** [comment]
I am not sure where the situation is currently but I feel the translator doesn't guarantee to support the IR with the optimizations. Does it work if you pass **_-O0_** to clang instead?

I assume the SPIR-V binary will be bigger but it can potentially be reduced using **spirv-opt**? Maybe @svenvh can provide more details?

**Comment by davidrohr** [comment]
You are right, it works with `-O0`. Already with `-O1` I get the error described above. But I feel this should be fixed in the tranlater, shouldn't it. Otherwise I don't know if it is of real use. I would assume the `-O3` might perform better optimization than the `spirv-opt`.

**Comment by AnastasiaStulova** [comment]
As far as I understand, this has not been a goal of the project from the beginning: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/203. I think the main reason is that many OpenCL toolchains don't optimise on SPIR-V level but convert into some native IR that they already supported before SPIR-V was introduced. I think for many toolchains it is LLVM-IR. But of course there is another aspect of SPIR-V binary size too.

Perhaps the goals should change... I have to say with wider use of C++ features in kernel languages the application will become more complex and have larger sizes so it can become more important to consume optimized IR. 

> I would assume the -O3 might perform better optimization than the spirv-opt.

I think so too, comparing the number of optimisations that exist in llvm-projects and SPIRV-Tools.

**Comment by AlexeySachkov** [comment]
@davidrohr, @AnastasiaStulova, the translator is actually able to propagate unknown LLVM intrinsics via regular function calls using `-spirv-allow-unknown-intrinsics` option introduced in #470 

You can try it, but please be aware that it might uncover some other issues down the stack, because some intrinsic which was previously lost during the translation will make it to device backend and it might not be expected/supported there.

**Comment by davidrohr** [comment]
@AlexeySachkov : Thx, I tested with the `-spirv-allow-unknown-intrinsics` option, but then it fails with
```
Not implemented!
UNREACHABLE executed at /home/qon/tmp9/llvm-project/llvm/projects/SPIRV-LLVM-Translator/lib/SPIRV/SPIRVWriter.cpp:479!
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /home/qon/tmp9/llvm-project/install/bin/llvm-spirv --spirv-allow-unknown-intrinsics test.bc -o test.spirv
1.      Running pass 'LLVMToSPIRV' on module 'test.bc'.
 #0 0x000056469e9b1730 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/qon/tmp9/llvm-project/llvm/lib/Support/Unix/Signals.inc:565:22
 #1 0x000056469e9b17e7 PrintStackTraceSignalHandler(void*) /home/qon/tmp9/llvm-project/llvm/lib/Support/Unix/Signals.inc:632:1
 #2 0x000056469e9af4bd llvm::sys::RunSignalHandlers() /home/qon/tmp9/llvm-project/llvm/lib/Support/Signals.cpp:71:20
 #3 0x000056469e9b10b4 SignalHandler(int) /home/qon/tmp9/llvm-project/llvm/lib/Support/Unix/Signals.inc:407:1
 #4 0x00007f60723f9810 __restore_rt (/lib64/libpthread.so.0+0x12810)
 #5 0x00007f6071e2ba21 raise (/lib64/libc.so.6+0x38a21)
 #6 0x00007f6071e15536 abort (/lib64/libc.so.6+0x22536)
 #7 0x000056469e9028eb bindingsErrorHandler(void*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) /home/qon/tmp9/llvm-project/llvm/lib/Support/ErrorHandling.cpp:222:55
 #8 0x000056469e00785d SPIRV::LLVMToSPIRV::transType(llvm::Type*) (.localalias) /home/qon/tmp9/llvm-project/llvm/projects/SPIRV-LLVM-Translator/lib/SPIRV/SPIRVWriter.cpp:479:3
 #9 0x000056469e0077b0 SPIRV::LLVMToSPIRV::transType(llvm::Type*) (.localalias) /home/qon/tmp9/llvm-project/llvm/projects/SPIRV-LLVM-Translator/lib/SPIRV/SPIRVWriter.cpp:475:29
#10 0x000056469e0082b2 SPIRV::LLVMToSPIRV::transFunctionDecl(llvm::Function*) /home/qon/tmp9/llvm-project/llvm/projects/SPIRV-LLVM-Translator/lib/SPIRV/SPIRVWriter.cpp:552:16
#11 0x000056469e01863a SPIRV::LLVMToSPIRV::translate() /home/qon/tmp9/llvm-project/llvm/projects/SPIRV-LLVM-Translator/lib/SPIRV/SPIRVWriter.cpp:3185:17
#12 0x000056469e004ffa SPIRV::LLVMToSPIRV::runOnModule(llvm::Module&) /home/qon/tmp9/llvm-project/llvm/projects/SPIRV-LLVM-Translator/lib/SPIRV/SPIRVWriter.cpp:134:10
#13 0x000056469e7cc59f (anonymous namespace)::MPPassManager::runOnModule(llvm::Module&) /home/qon/tmp9/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1550:20
#14 0x000056469e7c7764 llvm::legacy::PassManagerImpl::run(llvm::Module&) /home/qon/tmp9/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:541:13
#15 0x000056469e7cce51 llvm::legacy::PassManager::run(llvm::Module&) /home/qon/tmp9/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1678:1
#16 0x000056469e01c783 llvm::writeSpirv(llvm::Module*, SPIRV::TranslatorOpts const&, std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) /home/qon/tmp9/llvm-project/llvm/projects/SPIRV-LLVM-Translator/lib/SPIRV/SPIRVWriter.cpp:3931:9
#17 0x000056469df039f8 convertLLVMToSPIRV(SPIRV::TranslatorOpts const&) /home/qon/tmp9/llvm-project/llvm/projects/SPIRV-LLVM-Translator/tools/llvm-spirv/llvm-spirv.cpp:243:25
#18 0x000056469df068f5 main /home/qon/tmp9/llvm-project/llvm/projects/SPIRV-LLVM-Translator/tools/llvm-spirv/llvm-spirv.cpp:635:30
#19 0x00007f6071e16e6b __libc_start_main (/lib64/libc.so.6+0x23e6b)
#20 0x000056469df035da _start (/home/qon/tmp9/llvm-project/install/bin/llvm-spirv+0x11c5da)
Aborted
```
So I guess for now I'll just reduce the optimization level for my spirv tests to -O0, and use direct compilation for the target architecture.

**Comment by AlexeySachkov** [comment]
@davidrohr,

> @AlexeySachkov : Thx, I tested with the -spirv-allow-unknown-intrinsics option, but then it fails with
> ```
>  #8 0x000056469e00785d SPIRV::LLVMToSPIRV::transType(llvm::Type*) (.localalias) /home/qon/tmp9/llvm-project/llvm/projects/SPIRV-LLVM-Translator/lib/SPIRV/SPIRVWriter.cpp:479:3
> ```

Yes, this is another possible outcome: translating intrinsics as function calls is an easy part, but if there are some non-standard (from SPIR-V spec point of view) types, then it becomes impossible without hacking the source code of the translator or preparing SPIR-V extensions

**Comment by davidrohr** [comment]
Perhaps a bit unrelated, but could you then by chance tell me how I can use the clang backend for arm mali which I am targetting?
For amd vega I am using `--target=amdgcn-amd-amdhsa -mcpu=gfx906` but for arm I could only find the targets for the Cortex CPUs but not for the Mali GPUs.

**Comment by AlexeySachkov** [comment]
> but could you then by chance tell me how I can use the clang backend for arm mali which I am targetting?
For amd vega I am using --target=amdgcn-amd-amdhsa -mcpu=gfx906 but for arm I could only find the targets for the Cortex CPUs but not for the Mali GPUs.

Oh, I'm not familiar with that :) But probably @svenvh can help here?

**Comment by svenvh** [comment]
> Perhaps a bit unrelated, but could you then by chance tell me how I can use the clang backend for arm mali which I am targetting?
> For amd vega I am using `--target=amdgcn-amd-amdhsa -mcpu=gfx906` but for arm I could only find the targets for the Cortex CPUs but not for the Mali GPUs.

Clang/LLVM currently do not have support for Mali GPUs. You need the compiler that is included in the Mali driver. Depending on your platform, you may find a suitable driver [here](https://developer.arm.com/tools-and-software/graphics-and-gaming/mali-drivers/user-space), but these probably won't have all the latest features and fixes for the Clang and SPIR-V issues you have reported in the past.

**Comment by AnastasiaStulova** [comment]
Just to clarify a few more things the offline compilation options for Mali is:
1. Using upstream Clang and this translator to convert to SPIR-V binary which can be loaded by the Mali driver.
2. Using Mali offline compiler. The latests releases also include C++ for OpenCL via [cl_ext_cxx_for_opencl](https://www.khronos.org/registry/OpenCL/extensions/ext/cl_ext_cxx_for_opencl.html).

>Depending on your platform, you may find a suitable driver here, but these probably won't have all the latest features and fixes for the Clang and SPIR-V issues you have reported in the past.

Correct those seems quite old - I don't think there is a full SPIR-V support neither C++ for OpenCL.

**Comment by davidrohr** [comment]
ok, thx for the clarification. But that means the latest fixes for clang will also not be in the online compiler for Mali, so basically the only way I can run is using the upstream clang / translator chain.
But in that sense it is a bit unfortunate that I have to use -O0, since that will cost quite some performance I guess, while the main purpose of GPU computation is to boost performance.

**Comment by AnastasiaStulova** [comment]
> But in that sense it is a bit unfortunate that I have to use -O0, since that will cost quite some performance I guess, while the main purpose of GPU computation is to boost performance.

The SPIR-V binary is going to be optimised in the Mali driver btw. So it doesn't matter too much what frontend produces. The only issue is that loading the larger binary might take longer.

**Comment by MrSidims** [comment]
I believe, that the original request perfectly fits into https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/203 hence closing the issue. Feel free to re-open it if disagree.

PS We have an extension called SPV_INTEL_memory_access_aliasing (it's currently placed in https://github.com/intel/llvm/pull/4025 ), it adds the same aliasing scopes mechanism as LLVM does, but only for metadata. I believe, that it can be expanded by two more instructions, that will declare start and end of aliasing scopes to map these two experimental intrinsics, but there are no plans for that now and also I'm quite sure, that ARM GPU doesn't support this extension, but still you are welcome to contribute to it :)
