### ISSUE TITLE
Is it possible to build in-tree translator without clang target?

### ISSUE THREAD

**Issue by kurapov-peter** [KhronosGroup/SPIRV-LLVM-Translator#921]
Hi,

I'm building spirv translator (llvm_release_100, 3f9a2ba55c1c194c2831552fd37873965757a7f4) with llvm10 (release/10.x, ef32c611aa214dea855364efd7ba451ec5ec3f74) and would like to get rid of clang target (I do not intend to run any testing). I tried using cmake options from the llvm12 doc version:
-DLLVM_SPIRV_INCLUDE_TESTS=OFF
-DSPIRV_SKIP_CLANG_BUILD=ON

The latter is ignored by cmake and the former seem to not have any effect. 
Is it possible to exclude clang from llvm10 build (and install target as well)?

cmake command for reference:
```
cmake -DLLVM_ENABLE_PROJECTS="clang" \
    llvm-project/llvm/ \
    -DLLVM_TARGETS_TO_BUILD=X86 \
    -DCMAKE_BUILD_TYPE=Debug \
    -DBUILD_SHARED_LIBS=OFF \
    -DCMAKE_INSTALL_PREFIX=install/spirv \
    -DLLVM_ABI_BREAKING_CHECKS=FORCE_OFF \
    -DLLVM_USE_LINKER=gold \
    -DLLVM_ENABLE_ABI_BREAKING_CHECKS=0 
cmake --build . --parallel 8 --target install
```

cmake version 3.18.20200925-g7a4d84d
ubuntu 20.04 with GNU 8.4.0

Thanks,
Peter

**Comment by AlexeySachkov** [comment]
@kurapov-peter, you have explicitly enabled `clang` in your command line:

```
cmake -DLLVM_ENABLE_PROJECTS="clang" \
```

Try to remove this argument - in combination with `-DSPIRV_SKIP_CLANG_BUILD=ON` it should lead to the desired result

**Comment by kurapov-peter** [comment]
Does the trick, thanks!

p.s. I noticed the build system doesn't handle LLVM_ENABLE_PROJECTS.
