### ISSUE TITLE
LLVM readonly pointer qualifier mapping in SPIR-V

### ISSUE THREAD

**Issue by MrSidims** [KhronosGroup/SPIRV-LLVM-Translator#942]
Hi,

We are going to add translation of LLVM `readonly` pointer argument attribute. Naturally in SPIR-V it fits into `NoWrite` (3.19 Function Parameter Attribute). Problem that I faced during looking in the code is that `NoWrite` is already accupied by OpenCL metadata `kernel_arg_type_qual` in a case if a kernel pointer parameter was constant. The question is: can we use `NoWrite` for both cases or it's better to split them specification-wise? Aka is the const qualifier equivalent to the LLVM “readonly”? From my understanding it’s more like an enclosure as “const-qualified types may be placed in read-only memory by the compiler” and readonly pointer argument attribute explicitly says that the pointer points on read-only memory, and hence we can map both to `NoWrite` (note: in this case in when a `readonly` attribute appears in input LLVM IR, during reverse translation we would have both `kernel_arg_type_qual`  metadata and `readonly` attribute and vice versa.

**Comment by MrSidims** [comment]
tagging @svenvh @AlexeySotkin @bashbaug @jessicadavies-intel

**Comment by MrSidims** [comment]
tagging @AlexeySachkov

**Comment by StuartDBrady** [comment]
I believe the existing translation of `NoWrite` runs contrary to the SPIR-V spec and LLVM language reference. I have raised issue #977 for the removal of this translation.

Once this has been removed, that will leave the question of whether `NoWrite` is synonymous with LLVM IR's `readonly` attribute. My initial impression is that these are intended to be synonymous, but the SPIR-V specification lacks the wording needed to say this unequivocally, so a clarification will be needed with the SPIR working group.

**Comment by StuartDBrady** [comment]
Note: I haven't double-checked the behavior of the translator. It may well be valid to use `NoWrite` for pointees in the constant address space (i.e. the UniformConstant storage class) but I do not believe that is what is being talked about here, nor do I believe that using `NoWrite` would serve any useful purpose for UniformConstant pointers.

**Comment by MrSidims** [comment]
The issue is fixed
