### ISSUE TITLE
Internal capabilities saved in generated SPIRV

### ISSUE THREAD

**Issue by llandwerlin-intel** [KhronosGroup/SPIRV-LLVM-Translator#992]
It seems like some of the internal capabilities are making their way into the generated SPIRV binaries : 
```
enum InternalCapability {
  ICapOptimizationHintsINTEL = 5629,
  ICapMemoryAccessAliasingINTEL = 5910,
  ICapOptNoneINTEL = 6094
};
```

Should those be removed somehow?

**Comment by AlexeySachkov** [comment]
Hi @llandwerlin-intel,

> Should those be removed somehow?

No, this is by design. Internal here means that those hasn't been upstreamed to KhronosGroup/SPIRV-Headers repo yet to be included into the official `spirv.hpp` header.

However, those are pretty legal capabilities defined in corresponding SPIR-V extensions. If you don't want them to show up in resulting SPIR-V you need not to enable those extensions: by default all of them are disabled, so I assume that when you invoke the translator you pass `--spirv-ext=+all`.

**Comment by llandwerlin-intel** [comment]
I don't think I'm setting this option.

Here are some of the options passed : 
```
// By default, clang prefers to use modules to pull in the default headers,       
// which doesn't work with our technique of embedding the headers in our binary   
"-finclude-default-header",
// Add a default CL compiler version. Clang will pick the last one specified      
// on the command line, so the app can override this one.                         
"-cl-std=cl1.2",
// The LLVM-SPIRV-Translator doesn't support memset with variable size            
"-fno-builtin-memset",
// LLVM's optimizations can produce code that the translator can't translate      
"-O0",
// Ensure inline functions are actually emitted                                   
"-fgnu89-inline",
"-cl-std=cl2.0",
```

**Comment by AlexeySachkov** [comment]
> Here are some of the options passed :

Those looks like `clang` options, not the translator ones

**Comment by llandwerlin-intel** [comment]
Ah... lol : 

```
bool llvm::writeSpirv(Module *M, std::ostream &OS, std::string &ErrMsg) {
  SPIRV::TranslatorOpts DefaultOpts;
  // To preserve old behavior of the translator, let's enable all extensions                                                                
  // by default in this API                                                                                                                 
  DefaultOpts.enableAllExtensions();
  return llvm::writeSpirv(M, DefaultOpts, OS, ErrMsg);
}
```

**Comment by llandwerlin-intel** [comment]
I guess I should call a different function.

**Comment by AlexeySachkov** [comment]
> I guess I should call a different function.

Oh, yes. For the API we decided to preserve backward compatibility. You need to use the one which accepts `TranslatorOpts` instance and just not call `enableAllExtensions()`

**Comment by llandwerlin-intel** [comment]
Thanks.
